SonarSource/sonarlint-core

client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/common/CanceledException.java
client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/connected/ConnectedSonarLintEngine.java
core/src/main/java/org/sonarsource/sonarlint/core/ConnectedSonarLintEngineImpl.java
core/src/main/java/org/sonarsource/sonarlint/core/util/ProgressWrapper.java

java.util.concurrent.CancellationException gets wrapped, making it hard to catch it in client code.
We should probably not wrap java.util exceptions, but that would complicate too much the wrapping.

SLCORE-27 Add progress to update process

---

core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginCacheLoader.java
core/src/main/resources/plugins_min_versions.txt
core/src/main/resources/plugins_stream_support.txt
its/tests/projects/sample-xml/src/foo.xml
its/tests/src/test/java/its/ConnectedModeTest.java
its/tests/src/test/resources/xml-sonarlint.xml

Relates to [SONARXML-71](https://jira.sonarsource.com/browse/SONARXML-71) and associated PR: https://github.com/SonarSource/sonar-xml/pull/110
Requires fix #237
Changes are split in 2 commits:
* 1st commit to whitelist XML. This one will allow the XML plugin to have valid ITs testing compatibility.
* 2nd commit adds ITs relying on unreleased version of SonarXML.

SLCORE-221 Whitelist XML

---

core/pom.xml

I'm pretty sure no plugins is using JsonWriter in the SonarLint context. BTW I deprecated it on SQ side: https://jira.sonarsource.com/browse/SONAR-13198

Exclude JsonWriter from the plugin API

---

core/src/main/java/org/sonarsource/sonarlint/core/container/storage/FileMatcher.java
core/src/main/java/org/sonarsource/sonarlint/core/util/ReversePathTree.java
core/src/test/java/org/sonarsource/sonarlint/core/container/storage/FileMatcherTest.java
core/src/test/java/org/sonarsource/sonarlint/core/util/ReversePathTreeTest.java

Two optimizations:
* since in real life projects, many folders will have only one child, optimize the `Node` for the "one child" case
* use `Path` as key instead of converting back and forth `String` (minor)
Performance measures on my computer (Linux jdk 1.8.0_231), using test `FileMatcherTest#performance_test` (1M SQ files, 10k project files, very deep folders)
* before: ~20s, max heap: 3750Mb
* after: ~9s, max heap: 2250Mb

SLCORE-266 Optimize file matching algorithm

---

azure-pipelines.yml

We don't want to share the same cache between different jobs of the pipeline, because the content will not be the same depending on the Maven goal that is executed.

Use different caches per job

---

core/src/main/java/org/sonarsource/sonarlint/core/util/StringUtils.java
core/src/test/java/org/sonarsource/sonarlint/core/util/StringUtilsTest.java

equalsIgnoringTrailingSlash() method is used in VSCode language server also now

move methods to core since they are used in VSCode LS also

---

core/src/main/java/org/sonarsource/sonarlint/core/container/connected/update/IssueDownloader.java
core/src/test/java/org/sonarsource/sonarlint/core/container/connected/update/IssueDownloaderTests.java

Attempt to mitigate the 10k issues limit. I have not tested end to end, only verified that RESOLVED issues are coming first on this big SonarCloud project:
https://sonarcloud.io/api/issues/search?statuses=OPEN,CONFIRMED,REOPENED,RESOLVED&types=CODE_SMELL,BUG,VULNERABILITY&componentKeys=shipilev_jdk&organization=shipilev&s=STATUS&asc=false
Not sure it is very easy to add an integration test, because it is hard to control the order of issues.

SLCORE-198 Workaround for 10k limit

---

core/pom.xml

I did not add an IT, because it will be reverted soon, when we can update sonar-plugin-api to 9.0.

SLCORE-322 Support RulesDefinitionXmlLoader

---

its/tests/projects/sample-java-custom/pom.xml
its/tests/projects/sample-java/pom.xml
its/tests/src/test/java/its/ConnectedModeTest.java
its/tests/src/test/java/its/SonarCloudTest.java
its/tests/src/test/resources/java-sonarlint.xml

They have been moved to the XML plugin. We already have separate tests for Java and XML rules

Remove ITs checking XML issues are raised by the Java analyzer

---

azure-pipelines.yml

This reverts commit 9b4ba6900c4118b570ab734fdf510cc93abf4115.

Re-enable SonarCloud ITs after 6.6 release

---

analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisEngineConfiguration.java
analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/global/AnalysisExtensionInstaller.java
analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisEngineConfigurationTests.java
analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/global/AnalysisExtensionInstallerTests.java
analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/mediumtests/AnalysisEngineMediumTests.java
core/src/main/java/org/sonarsource/sonarlint/core/ConnectedSonarLintEngineImpl.java
core/src/main/java/org/sonarsource/sonarlint/core/StandaloneSonarLintEngineImpl.java
its/tests/src/test/java/its/SonarQubeCommunityEditionTests.java

The TS sensor was manually excluded to handle the case where TS language was disabled but JS was enabled. This is not the case anymore as both are usually enabled at the same time, and the workaround does not work anymore since last SonarJS as both sensors have been merged.

Remove workaround for SonarTS

---

.cirrus.yml

The QA should not wait for other test jobs to complete.

QA should not wait for unit tests to start

---

.cirrus.yml

Restrict build to PR, default, dogfood and maintained branches, excluding working branches with no PR.

BUILD-3061 do not build working branches with no PR

---

its/tests/pom.xml
pom.xml

I've read the release notes for [32.0.0](https://github.com/google/guava/releases/tag/v32.0.0), [32.0.1](https://github.com/google/guava/releases/tag/v32.0.1), [32.1.0](https://github.com/google/guava/releases/tag/v32.1.0), [32.1.1](https://github.com/google/guava/releases/tag/v32.1.1) and there seem to be no groundbreaking changes affecting us. As a disclaimer: My knowledge of the use of Guava in SLCORE is very limited, therefore this is only my humble opinion.
Some releases introduced issues fixed in later releases, therefore the jump to 32.1.1.

Update Guava to 32.1.1

---

client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/rules/AbstractRuleDto.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/rules/EffectiveRuleDetailsDto.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/rules/RuleDefinitionDto.java
core/src/test/java/mediumtest/StandaloneRulesMediumTests.java

This will simplify working with the rule information on the *SonarLint for Eclipse* side and maybe on the other IDEs as well.

Shared ancestor for RuleDefinitionDto and EffectiveRuleDetailsDto

---

.cirrus.yml

Fix build conditions to not build branches with no PR.
Fix ONLY_IF_EXCEPT_NIGHTLY
Remove ONLY_PR_AND_MAINTAINED_BRANCHES duplicating ONLY_IF_EXCEPT_NIGHTLY
Fix confirmed by
- https://cirrus-ci.com/build/5642988039176192 (no run for the single branch)
- https://cirrus-ci.com/build/6577892897849344 (run the branch after PR creation)

BUILD-3668 fix build conditions (no branch without PR)

---

pom.xml

Updating the library with the [fixes](https://github.com/Hakky54/sslcontext-kickstart/pull/370) regarding the [macOS issues](https://github.com/Hakky54/sslcontext-kickstart/issues/369).

SLCORE-550: Update sslcontext-kickstart

---

client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/issue/CheckAnticipatedStatusChangeSupportedParams.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/issue/CheckAnticipatedStatusChangeSupportedResponse.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/issue/IssueService.java
core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueServiceImpl.java
core/src/test/java/mediumtest/issues/CheckAnticipatedStatusChangeSupportedMediumTests.java

In order to be used on _SonarLint for Eclipse_, general information about a connection supporting the anticipated transitions should be available. Rather than on an issue level, this information is gathered to configure markers at once and not per marker, saving computing time.
Medium tests are added in order to check every possible scenario the new interface method might face.

SLE-741: Server info about anticipated transitions

---

core/src/main/java/org/sonarsource/sonarlint/core/ConnectedSonarLintEngineImpl.java
core/src/main/java/org/sonarsource/sonarlint/core/client/api/connected/ConnectedSonarLintEngine.java
its/tests/src/test/java/its/SonarCloudTests.java
its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/IssueStoreReader.java
server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerConnection.java
server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/IssueStoreReaderTests.java

To be able to re-open Taint Vulnerabilities from within the IDE we require the option to display the resolved issue again.

SLCORE-589: Make resolved Taint Issues available

---

core/src/main/java/org/sonarsource/sonarlint/core/websocket/SonarCloudWebSocket.java
http/src/main/java/org/sonarsource/sonarlint/core/http/WebSocketClient.java
medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java

Closing the executor service too early leads to interrupting the thread that is doing the reconnect. We should close the executor only after the reconnect handler has been executed.

SLCORE-603 Fix interrupted exception when reconnecting after close

---

medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java

Since the notification processing is asynchronous, we have a risk of race condition. In fact, calling the event is not needed anymore, as the backend initialization will create the telemetry file (probably for the new code period).

Fix Overlapping exception in TelemetryMediumTest

---

.cirrus.yml

Run SC its with java 17 due to "The version of Java (11.0.21) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later."

Run SC its with java 17

---

client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/issue/ResolutionStatus.java
commons/src/main/java/org/sonarsource/sonarlint/core/commons/IssueStatus.java
commons/src/main/java/org/sonarsource/sonarlint/core/commons/Transition.java
core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueServiceImpl.java
medium-tests/src/test/java/mediumtest/issues/CheckResolutionStatusChangePermittedMediumTests.java
server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/issue/IssueApi.java

With SonarQube 10.4 and coming SonarCloud the transitions for resolving issues will be changed from **Won't fix** to **Accept**.

SLCORE-647: "Won't fix" becomes "Accept"

---

client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/SonarLintBackend.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/usertoken/RevokeTokenParams.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/backend/usertoken/UserTokenService.java
client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/client/connection/AssistCreatingConnectionParams.java
core/src/main/java/org/sonarsource/sonarlint/core/ServerApiProvider.java
core/src/main/java/org/sonarsource/sonarlint/core/SonarLintBackendImpl.java
core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowHotspotOrIssueRequestHandler.java
core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java
core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/StatusRequestHandler.java
core/src/main/java/org/sonarsource/sonarlint/core/http/ConnectionUnawareHttpClientProvider.java
core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java
core/src/main/java/org/sonarsource/sonarlint/core/usertoken/UserTokenServiceImpl.java
core/src/test/java/org/sonarsource/sonarlint/core/ServerApiProviderTests.java
core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandlerTest.java
its/tests/src/test/java/its/SonarCloudTests.java
its/tests/src/test/java/its/SonarQubeCommunityEditionTests.java
medium-tests/src/test/java/mediumtest/EmbeddedServerMediumTests.java
medium-tests/src/test/java/mediumtest/UserTokenMediumTests.java
server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApi.java
server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/usertokens/UserTokensApi.java

When using the "Open in IDE" feature on SonarQube, we want to get a token (if possible) for an automated connected mode setup. It should still work with older SonarQube servers not able to generate a token as well as opening Security Hotspots in the IDE - this feature won't provide a token.
The changes on the SonarQube side were already done (**old SonarLint - new SonarQube** and **new SonarLint - old SonarQube** will work).
Follow-up ticket: [SLCORE-666 Make token revocation transparent for the client](https://sonarsource.atlassian.net/browse/SLCORE-666)

SLCORE-665: Automatic connected mode setup

---

server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java
server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java
server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerConnection.java
server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizerTests.java

There was an issue that connecting SonarLint to SQ 10.3 and earlier worked the same as before. However, with 10.4, the `sonar-text` analyzer wasn't downloaded anymore because it was still seen as embedded while the `PluginsSynchonizer` was synchronizing the plug-ins for the connection.
The [first approach](https://github.com/SonarSource/sonarlint-core/commit/6aeaf961919d1eb5cd880b50c9da41168d119e1d) to mitigate this issue only worked when the connection was established; the IDE was closed and then opened again for the synchronization to start again. This was due to the check to remove the embedded instance of `sonar-text` not being able to access the server information yet to check the SQ version.
The synchronization of the SQ server information was not finished the first time, but when …

SLCORE-668: Fix download of sonar-text

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/commons/DebounceComputer.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/commons/SmartCancelableLoadingCache.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/commons/SmartCancelableLoadingCacheTests.java

I noticed that the listener can be called more times than expected, in case of highly concurrent refreshes. This time it was easy to reproduce with a test.

Debounce properly the calls to the listener

---

its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java

The rule description of javasecurity:S2083 was updated in SQ 10.4

Fix failing test consecutive to analyzer metadata update

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingSuggestionProvider.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionSuggestionProvider.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/BindingSuggestionProviderTests.java
client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java
client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientImpl.java
its/tests/src/test/java/its/MockSonarLintRpcClientDelegate.java
medium-tests/src/test/java/mediumtest/ConnectionSuggestionMediumTests.java
medium-tests/src/test/java/mediumtest/SharedConnectedModeSettingsMediumTests.java
medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java
medium-tests/src/test/java/mediumtest/sloop/SloopLauncherTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcClient.java

- Since `ConnectionSuggestionProvider` was listening to the same events at the `BindingSuggestionProvider`, it is not useful to keep the listeners in `BindingSuggestionProvider` because anyway the connection provider will fallback to the binding provider if there is no connection to be suggested
- Avoid the `BindingSuggestionProvider` to propose a binding while the connection is being created on the client side
- Fix test error with trailing '/'

Avoid sending multiple binding suggestions

---

its/plugins/java-custom-rules/pom.xml

Declare the <requiredForLanguages> tag so that the custom Java plugin used in tests is considered optional. This prevents the plugin from being loaded at the beginning of scanner execution, because the SonarJava dependency is not loaded either

Fix IT failing since SQ 10.5 release

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionSuggestionProvider.java
client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java
client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientImpl.java
its/plugins/java-custom-rules/pom.xml
its/tests/src/test/java/its/MockSonarLintRpcClientDelegate.java
medium-tests/src/test/java/mediumtest/ConnectionSuggestionMediumTests.java
medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java
medium-tests/src/test/java/mediumtest/sloop/SloopLauncherTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcClient.java

Since the `suggestConnection` only shows a notification, it's purely asynchronous and we cannot wait.
I'd suggest using `didUpdateBinding` and modifying the `bindingSuggestionDisabled` field on the client side before and after processing the binding.

Remove useless usage of CompletableFuture for suggesting connection

---

backend/embedded/javadoc/README.md
backend/embedded/pom.xml
client/embedded/javadoc/README.md
client/embedded/pom.xml
pom.xml

There are two commits:
1. Remove embedded modules from the parent pom because we don't use them currently. 
2. Create a dummy Javadoc jar for these modules to pass the deploy-check in case we decide to use them in the future
- It doesn't generate Javadoc by default because these modules don't have any source files.

SLCORE-733 Publish artifacts needed by clients to Maven Central

---

.cirrus.yml

This happens on the promotion due to the Maven Cache not having enough memory to load all the modules built (e.g., backend ones having a JRE are too big). [Here](https://cirrus-ci.com/task/4630130524422144) is a failing task.
I had the bottleneck on SLE also at some point, so I re-used [its](https://github.com/SonarSource/sonarlint-eclipse/blob/master/.cirrus.default.yml#L277-L299) configuration that was found together with RE.

NO-JIRA: Fix pipeline running OOM

---

client/java-client-osgi/java-client-osgi.bnd

The OSGi bundle created via Bndtools copied the exported packages from the included resources (other modules' JAR archives) into the shaded one.
After getting in touch with the Bndtools developers a simpler solution was found (that [lacks documentation](https://bnd.bndtools.org/instructions/exportcontents.html)) that does not include copying exported packages from the included JAR archives.
A small explanation of the `Export-Packages` manifest header and how it is computed additionally using the `-exportcontents` instruction can be found [HERE](https://bnd.discourse.group/t/more-information-about-exportcontent/214/2)!

SLCORE-737: Simplify / remove duplication

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingClueProvider.java
medium-tests/pom.xml
medium-tests/src/test/java/mediumtest/ConnectionSuggestionMediumTests.java
medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java

In the SonarLint configuration file, it's possible to have content with a "valid" connection config with empty values. Today, we report these empty lines as suggestions when we detect such config files. This fix ensures that we will only show useful suggestions for the user in this case.

SLCORE-774 Do not send empty string suggestions to the client

---

API_CHANGES.md
backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowHotspotRequestHandler.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandlerTests.java
medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/adapter/EitherSonarQubeSonarCloudConnectionParamsAdapterFactory.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/AssistCreatingConnectionParams.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/SonarCloudConnectionParams.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/SonarQubeConnectionParams.java

SLCORE-818 Provide connection parameters for SC while opening an issue in IDE

---

backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/loading/SonarPluginRequirementsChecker.java
backend/plugin-commons/src/test/java/org/sonarsource/sonarlint/core/plugin/commons/loading/SonarPluginRequirementsCheckerTests.java

This reverts commit e2fa6ffdab029a38c26d30cd3fcaacdde843fb54 so that newer versions of SonarLint are compatible with older SonarQube servers (with older DBD versions).

Revert "SLCORE-672 remove explicit dependency check for DBD plugins"

---

backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/PluginsStorage.java
backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ProtobufFileUtil.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisReadinessMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/AnalysysForcedByClientMediumTests.java
medium-tests/src/test/java/mediumtest/file/ClientFileExclusionsMediumTests.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotEventsMediumTests.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotLocalDetectionSupportMediumTests.java
medium-tests/src/test/java/mediumtest/issues/IssueEventsMediumTests.java
medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java
medium-tests/src/test/java/mediumtest/server/events/ServerSentEventsMediumTests.java
medium-tests/src/test/java/mediumtest/synchronization/ConnectionSyncMediumTests.java
medium-tests/src/test/java/mediumtest/synchronization/PluginSynchronizationMediumTests.java
medium-tests/src/test/java/mediumtest/taint/vulnerabilities/TaintVulnerabilityEventsMediumTests.java
medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java
medium-tests/src/test/java/mediumtest/tracking/SecurityHotspotTrackingMediumTests.java
medium-tests/src/test/java/testutils/AnalysisUtils.java
medium-tests/src/test/java/testutils/LogTestStartAndEnd.java
medium-tests/src/test/java/testutils/sse/SSEServer.java
medium-tests/src/test/java/testutils/sse/SSEServlet.java

Main changes:
- Introducing ServerSentEvent server in tests to send server-sent events since WireMock doesn't allow sending them by command and relies on timeout.
- Change PluginStorage to avoid race condition between plugin downloading and cleanup.
- Improve assertions and logging for tests.

SLCORE-869 Flaky tests

---

API_CHANGES.md

This content was twice in the file for the 10.4 release. The newer one is still kept above.

NO-JIRA: Removed doublet from API_CHANGES.md

---

client/java-client-utils/src/main/java/org/sonarsource/sonarlint/core/client/utils/GitUtils.java
client/java-client-utils/src/test/java/org/sonarsource/sonarlint/core/client/utils/GitUtilsTests.java

This reverts the removal of the GitUtils class inside the "sonarlint-java-client-utils" module that is still used on SonarLint for Eclipse. As no replacement was introduced, this had to be put back.
Referencing the commit that removed it: [082c0cac9a6a873b4c1d71782dd0433a5d45d47e](https://github.com/SonarSource/sonarlint-core/commit/082c0cac9a6a873b4c1d71782dd0433a5d45d47e#diff-f5665894ddbe8c7c0d31c280d252be39012e245178ab1ddf1f659afdb2afabcf)

SLCORE-835: Revert removing GitUtils (and test)

---

pom.xml

This is a temporary workaround for https://sonarsource.atlassian.net/browse/BUILD-6160 to allow releasing.
A later fix will be committed in the parent-oss POM and this workaround will be removable.
Issue reproduced by https://github.com/SonarSource/sonarlint-core/pull/1089/checks?check_run_id=29575053853
Workaround tested with https://github.com/SonarSource/sonarlint-core/pull/1089/checks?check_run_id=29575934360

BUILD-6160 downgrade maven-javadoc-plugin to 3.8.0

---

client/java-client-dependencies/pom.xml
client/java-client-osgi/pom.xml
pom.xml

[BUILD-6160](https://sonarsource.atlassian.net/browse/BUILD-6160)
Proper fix to the broken promotion.
The breakage was due to duplicated Javadoc artifacts generated and attached to the build.
As of maven-javadoc-plugin 3.10.0, the empty Javadoc is generated by default.
As suggested in https://github.com/apache/maven-javadoc-plugin/pull/65 by the following sentence:
> Add generateIfEmpty property to javadoc:jar goal, defaulting to false for backwards compatibility.
maven-javadoc-plugin 3.10.0 defaults to true, with no customization property.
This fix was confirmed by https://cirrus-ci.com/build/5445574646824960
[BUILD-6160]: https://sonarsource.atlassian.net/browse/BUILD-6160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6160 emptyJavadoc

---

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/metricspayload/TelemetryMetricsDimension.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/metricspayload/TelemetryMetricsPayload.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/metricspayload/TelemetryMetricsValue.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/metricspayload/TelemetryMetricsValueGranularity.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/metricspayload/TelemetryMetricsValueType.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/metricspayload/package-info.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java

[SLCORE-938](https://sonarsource.atlassian.net/browse/SLCORE-938)
[SLCORE-938]: https://sonarsource.atlassian.net/browse/SLCORE-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-938 + SLCORE-940 Implement telemetry metrics system

---

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitUtilsTest.java

[SLCORE-942](https://sonarsource.atlassian.net/browse/SLCORE-942)
When no ".gitignore" file was found, just inform about it instead of showing the error message and and misleading information that is only relevant for when actual exceptions happen.
[SLCORE-942]: https://sonarsource.atlassian.net/browse/SLCORE-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-942: Don't show exception when no Gitignore found

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java

[SLCORE-937](https://sonarsource.atlassian.net/browse/SLCORE-937)
Skip the check for symbolic links and Windows shortcuts when filtering URIs for the analysis for protocols / schemes that are not supporting such operations.
If not skipping but excluding these URIs then using other protocols would never be possible.
[SLCORE-937]: https://sonarsource.atlassian.net/browse/SLCORE-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-937: Don't fail when checks not possible

---

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/global/GlobalTempFolderProvider.java

[SLCORE-935](https://sonarsource.atlassian.net/browse/SLCORE-935)
We clean the temporary directory more often to have smaller footprint than only doing it for files older than 21 days.
[SLCORE-935]: https://sonarsource.atlassian.net/browse/SLCORE-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-935: Clean temp directory after 7 days

---

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/SonarLintGitIgnore.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/FileUtils.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitUtilsTest.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/LogTestStartAndEnd.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/AnalysysForcedByClientMediumTests.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotEventsMediumTests.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotLocalDetectionSupportMediumTests.java
medium-tests/src/test/java/mediumtest/issues/IssueEventsMediumTests.java
medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java
medium-tests/src/test/java/mediumtest/server/events/ServerSentEventsMediumTests.java
medium-tests/src/test/java/mediumtest/synchronization/PluginSynchronizationMediumTests.java
medium-tests/src/test/java/mediumtest/taint/vulnerabilities/TaintVulnerabilityEventsMediumTests.java

In case the git repo path is the same as the base project dir (which should be very often), `gitRepoRelativeProjectBaseDir` was resolved to an empty path, so the file path was resolved as an absolute one, not a relative one. So, matching wasn't working.
I've tested manually with the provided reproducer repo:
https://github.com/jblievremont/sample-gitignore-priority
Now it behaves as expected.
UPD:
The problem was that we were supposed to do very different things for the case when we used base project dir as a base and in the case when it's a git directory relative to the base project dir. We need to resolve the relative file path to compute if it's ignored, but we should do it in a bit different way. Previously, we had one code doing it, and it was incorrect for one case or another.

SLCORE-919 Files are ignored by application of .gitignore when they should not

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java

[SLCORE-969](https://sonarsource.atlassian.net/browse/SLCORE-969)
When a user is running an analysis, it is not clear why certain files get filtered out.
This should not be the case, and therefore, for every distinct filter applied, we log the file URIs that are filtered out and display them in the debug logs.
[SLCORE-969]: https://sonarsource.atlassian.net/browse/SLCORE-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-969: Debug logs for filtered out files for analysis

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetails.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetailsAdapter.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/rules/RulesServiceTests.java
backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/rules/RulesApi.java
backend/server-api/src/main/proto/sonarqube/ws-rules.proto

[SLCORE-999](https://sonarsource.atlassian.net/browse/SLCORE-999)
[SLCORE-999]: https://sonarsource.atlassian.net/browse/SLCORE-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-999 Store custom impacts when synchronizing rules

---

backend/commons/pom.xml
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitUtilsTest.java

[SLCORE-927](https://sonarsource.atlassian.net/browse/SLCORE-927)
[SLCORE-927]: https://sonarsource.atlassian.net/browse/SLCORE-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-927 Reactivate git blaming for bare repositories

---

backend/analysis-engine/pom.xml
backend/cli/pom.xml
backend/commons/pom.xml
backend/core/pom.xml
backend/http/pom.xml
backend/plugin-api/pom.xml
backend/plugin-commons/pom.xml
backend/rpc-impl/pom.xml
backend/rule-extractor/pom.xml
backend/server-api/pom.xml
backend/server-connection/pom.xml
backend/slf4j-sonar-log/pom.xml
backend/telemetry/pom.xml
buildSrc/maven-shade-ext-bnd-transformer/pom.xml
client/java-client-dependencies/pom.xml
client/java-client-osgi/pom.xml
client/java-client-utils/pom.xml
client/rpc-java-client/pom.xml
its/plugins/custom-sensor-plugin/pom.xml
its/plugins/global-extension-plugin/pom.xml
its/plugins/java-custom-rules/pom.xml
its/pom.xml
its/tests/pom.xml
medium-tests/pom.xml
pom.xml
report-aggregate/pom.xml
rpc-protocol/pom.xml

[SLCORE-1030](https://sonarsource.atlassian.net/browse/SLCORE-1030)
[SLCORE-1030]: https://sonarsource.atlassian.net/browse/SLCORE-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1030 Prepare for next development iteration

---

client/java-client-dependencies/pom.xml
client/java-client-osgi/java-client-osgi.bnd
client/java-client-osgi/pom.xml
its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java

[SLCORE-1029](https://sonarsource.atlassian.net/browse/SLCORE-1029)
Shading/relocating JGit (and its required dependency SLF4J) into the OSGi bundle in order to work properly on Eclipse again for the patch release 10.9.1 planned, see [SonarSource/sonarlint-eclipse#761](https://github.com/SonarSource/sonarlint-eclipse/pull/761).
On SonarLint for Eclipse the incompatible dependency with EGit/JGit (bundled with the IDE, not from us, requiring Java 17 now) is dropped and replaced by this.
In order to satisfy the pipeline gods a test was fixed in a separate cherry-picked commit for ITs against SQ DEV.
[SLCORE-1029]: https://sonarsource.atlassian.net/browse/SLCORE-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1029: Shade/relocate JGit into OSGi bundle

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/OrganizationsCache.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/hotspot/HotspotService.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotLocalDetectionSupportMediumTests.java

[SLCORE-1031](https://sonarsource.atlassian.net/browse/SLCORE-1031)
[SLCORE-1031]: https://sonarsource.atlassian.net/browse/SLCORE-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1031 Modify label for missing binding on hotspots

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/local/only/XodusLocalOnlyIssueStore.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/storage/XodusPurgeUtils.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/XodusKnownFindingsStore.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/local/only/XodusKnownFindingsStoreTests.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/local/only/XodusLocalOnlyIssueStoreTests.java

[SLCORE-858](https://sonarsource.atlassian.net/browse/SLCORE-858)
[SLCORE-858]: https://sonarsource.atlassian.net/browse/SLCORE-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-858 SonarLint storage is growing after restart

---

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/log/LogOutputDelegator.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/log/LogOutputDelegatorTests.java

[SLCORE-1038](https://sonarsource.atlassian.net/browse/SLCORE-1038)
[SLCORE-1038]: https://sonarsource.atlassian.net/browse/SLCORE-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1038 Remove workaround for suppressing noisy analyzer logs

---

.cirrus.yml

[SLCORE-1048](https://sonarsource.atlassian.net/browse/SLCORE-1048)
This is done by other repos as well for now until Orchestrator is fixed.
[SLCORE-1048]: https://sonarsource.atlassian.net/browse/SLCORE-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1048 Use fixed development reference for SQ instead of version number

---

API_CHANGES.md
backend/core/src/main/java/org/sonarsource/sonarlint/core/fs/ClientFileSystemService.java
its/tests/src/test/java/its/FileExclusionTests.java
its/tests/src/test/java/its/SonarCloudTests.java
its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
its/tests/src/test/java/its/SonarQubeEnterpriseEditionTests.java
its/tests/src/test/java/its/StandaloneTests.java
medium-tests/src/test/java/mediumtest/BindingSuggestionsMediumTests.java
medium-tests/src/test/java/mediumtest/ConnectionSuggestionMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/file/DidUpdateFileSystemParams.java

[SLCORE-1039](https://sonarsource.atlassian.net/browse/SLCORE-1039)
[SLCORE-1039]: https://sonarsource.atlassian.net/browse/SLCORE-1039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1039 Differentiate added/modified files in FS API

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java

[SLCORE-1052](https://sonarsource.atlassian.net/browse/SLCORE-1052)
[SLCORE-1052]: https://sonarsource.atlassian.net/browse/SLCORE-1052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1052 Set the correct impacts if it's empty on the server

---

backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java

[SLCORE-1049](https://sonarsource.atlassian.net/browse/SLCORE-1049)
On SonarQube Cloud OR SonarQube Server 10.4+ we download specific version of the SonarText analyzer in Connected Mode.
[SLCORE-1049]: https://sonarsource.atlassian.net/browse/SLCORE-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1049: Fix condition for using SonarText from server

---

backend/analysis-engine/pom.xml
backend/cli/pom.xml
backend/commons/pom.xml
backend/core/pom.xml
backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java
backend/http/pom.xml
backend/plugin-api/pom.xml
backend/plugin-commons/pom.xml
backend/rpc-impl/pom.xml
backend/rule-extractor/pom.xml
backend/server-api/pom.xml
backend/server-connection/pom.xml
backend/slf4j-sonar-log/pom.xml
backend/telemetry/pom.xml
buildSrc/maven-shade-ext-bnd-transformer/pom.xml
client/java-client-dependencies/pom.xml
client/java-client-osgi/pom.xml
client/java-client-utils/pom.xml
client/rpc-java-client/pom.xml
its/plugins/custom-sensor-plugin/pom.xml
its/plugins/global-extension-plugin/pom.xml
its/plugins/java-custom-rules/pom.xml
its/pom.xml
its/tests/pom.xml
medium-tests/pom.xml
pom.xml
report-aggregate/pom.xml
rpc-protocol/pom.xml

[SLCORE-1064](https://sonarsource.atlassian.net/browse/SLCORE-1064)
[SLCORE-1064]: https://sonarsource.atlassian.net/browse/SLCORE-1064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1064 Fix the loading of sonar-text analyzer in Connected Mode

---

API_CHANGES.md
backend/commons/pom.xml
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/log/LogOutputDelegator.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/DogfoodEnvironmentDetectionService.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/MonitoringInitializationParams.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/MonitoringService.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/package-info.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java
backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/DogfoodingRpcServiceDelegate.java
backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/SonarLintRpcServerImpl.java
its/tests/src/test/java/its/FileExclusionTests.java
its/tests/src/test/java/its/SonarCloudTests.java
its/tests/src/test/java/its/SonarQubeCommunityEditionTests.java
its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
its/tests/src/test/java/its/SonarQubeEnterpriseEditionTests.java
its/tests/src/test/java/its/StandaloneTests.java
medium-tests/pom.xml
medium-tests/src/test/java/mediumtest/InitializationMediumTests.java
medium-tests/src/test/java/mediumtest/dogfooding/DogfoodingRpcServiceMediumTests.java
medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java
medium-tests/src/test/java/mediumtest/fixtures/SonarLintTestRpcServer.java
medium-tests/src/test/java/mediumtest/sloop/SloopLauncherTests.java
medium-tests/src/test/java/mediumtest/sloop/SloopLauncherWithJreTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcServer.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/dogfooding/DogfoodingRpcService.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/dogfooding/IsDogfoodingEnvironmentResponse.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/dogfooding/package-info.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/initialize/FeatureFlagsDto.java

[SLCORE-1055](https://sonarsource.atlassian.net/browse/SLCORE-1055)
[SLCORE-1055]: https://sonarsource.atlassian.net/browse/SLCORE-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1055 sentry integration

---

its/tests/src/test/java/its/AbstractConnectedTests.java
its/tests/src/test/java/its/SonarQubeCommunityEditionTests.java
its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java

[SLCORE-1101](https://sonarsource.atlassian.net/browse/SLCORE-1101)
[SLCORE-1101]: https://sonarsource.atlassian.net/browse/SLCORE-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1101 stop using deprecated sonar.password field

---

test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java

[SLCORE-1119](https://sonarsource.atlassian.net/browse/SLCORE-1119)
[SLCORE-1119]: https://sonarsource.atlassian.net/browse/SLCORE-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1119 Fix code smells

---

client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SloopLauncher.java
client/rpc-java-client/src/test/java/org/sonarsource/sonarlint/core/rpc/client/SloopLauncherTests.java

[SLCORE-1105](https://sonarsource.atlassian.net/browse/SLCORE-1105)
[SLCORE-1105]: https://sonarsource.atlassian.net/browse/SLCORE-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1105 Avoid displaying the Java icon in the taskbar on MacOS

---

client/java-client-dependencies/pom.xml
client/java-client-osgi/java-client-osgi.bnd
client/java-client-osgi/pom.xml
client/java-client-utils/pom.xml
client/rpc-java-client/pom.xml
pom.xml
rpc-protocol/pom.xml

[SLCORE-716](https://sonarsource.atlassian.net/browse/SLCORE-716)
Remove the `sonarlint-commons` module from the OSGi bundle that is used by SonarQube for Eclipse as it is not required anymore.
Move all but the modules required for the OSGi bundle to Java 17.
[SLCORE-716]: https://sonarsource.atlassian.net/browse/SLCORE-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-716: Move most of the code base to Java 17

---

.cirrus.yml

[SLCORE-716](https://sonarsource.atlassian.net/browse/SLCORE-716)
Because the Docker image was setting the Java version conditionally on Cirrus CI.
[SLCORE-716]: https://sonarsource.atlassian.net/browse/SLCORE-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-716: Mend / Promote task to use Java 17

---

client/java-client-utils/src/main/java/org/sonarsource/sonarlint/core/client/utils/GitUtils.java

[SLCORE-1140](https://sonarsource.atlassian.net/browse/SLCORE-1140)
Currently when users are not in a Git repository there is an error logged for every action trying to invoke Git. This is too noisy and misleading as this is not an actual error.
[SLCORE-1140]: https://sonarsource.atlassian.net/browse/SLCORE-1140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1140: Don't log an error when not in Git repository

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConfigurationService.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/ConfigurationServiceTests.java

[SLCORE-1141](https://sonarsource.atlassian.net/browse/SLCORE-1141)
Currently, when users close projects in the Eclipse IDE or when projects are removed on disk but the workspace reference is still in the workspace and the user then deletes this very project from the workspace, an error is logged.
As this is a valid situation in Eclipse, rather log a debug message and not an error as nothing is actually failing.
[SLCORE-1141]: https://sonarsource.atlassian.net/browse/SLCORE-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1141: Don't log an error when closed projects removed

---

backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AnalyzerConfigurationStorage.java
backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/PluginsStorage.java

[SLCORE-1153](https://sonarsource.atlassian.net/browse/SLCORE-1153)
This is just a noisy error when creating a connection and binding a project to determine whether the analysis is yet ready. 
[SLCORE-1153]: https://sonarsource.atlassian.net/browse/SLCORE-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1153: Don't log an error on ProtBuf check for analysis readiness

---

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/StringUtils.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/StringUtilsTests.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandler.java

[SLCORE-1144](https://sonarsource.atlassian.net/browse/SLCORE-1144)
[SLCORE-1144]: https://sonarsource.atlassian.net/browse/SLCORE-1144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1144 Fix SSF-699

---

API_CHANGES.md
backend/core/src/main/java/org/sonarsource/sonarlint/core/connection/ServerConnection.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/ConnectionManagerTests.java
medium-tests/src/test/java/mediumtest/synchronization/ConnectionSyncMediumTests.java

[SLCORE-1145](https://sonarsource.atlassian.net/browse/SLCORE-1145)
[SLCORE-1145]: https://sonarsource.atlassian.net/browse/SLCORE-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1145 Notify client only on 401 response from server

---

API_CHANGES.md
backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/command/AnalyzeCommand.java
backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/sensor/SensorsExecutor.java
backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/module/ModuleContainer.java
backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/analysis/sensor/SensorsExecutorTests.java
backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/mediumtests/AnalysisEngineMediumTests.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/MonitoringService.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/Span.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/Trace.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java
medium-tests/src/test/java/mediumtest/monitoring/MonitoringMediumTests.java
medium-tests/src/test/java/mediumtest/monitoring/ThrowingPhpSensor.java

[SLCORE-1149](https://sonarsource.atlassian.net/browse/SLCORE-1149)
[SLCORE-1149]: https://sonarsource.atlassian.net/browse/SLCORE-1149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1149 Trace execution of analysis requests and sensors

---

medium-tests/src/test/java/mediumtest/connection/ConnectionGetProjectNameByKeyMediumTests.java
medium-tests/src/test/java/mediumtest/connection/OrganizationMediumTests.java

[SLCORE-1166](https://sonarsource.atlassian.net/browse/SLCORE-1166)
[SLCORE-1166]: https://sonarsource.atlassian.net/browse/SLCORE-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1166 Fix quality gate

---

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/BlameParser.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/ProcessWrapperFactory.java
backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/WinGitUtils.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitUtilsTest.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtilsTest.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/ProcessWrapperFactoryTests.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java
medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java
pom.xml

[SLCORE-1133](https://sonarsource.atlassian.net/browse/SLCORE-1133)
Cache the Git executable and leverage it if possible first for blaming. If there is an issue, fallback to the implementation based on `git-files-blame` / `JGit`.
Supersedes #1192 
[SLCORE-1133]: https://sonarsource.atlassian.net/browse/SLCORE-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1133: Rely on native Git if possible for blaming

---

.gitignore
API_CHANGES.md
backend/core/src/main/java/org/sonarsource/sonarlint/core/SonarCloudActiveEnvironment.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/SonarCloudActiveEnvironmentTests.java
its/tests/src/test/java/its/SonarCloudTests.java
medium-tests/src/test/java/mediumtest/SharedConnectedModeSettingsMediumTests.java
medium-tests/src/test/java/mediumtest/connection/ConnectionGetAllProjectsMediumTests.java
medium-tests/src/test/java/mediumtest/connection/ConnectionGetProjectNameByKeyMediumTests.java
medium-tests/src/test/java/mediumtest/connection/ConnectionValidatorMediumTests.java
medium-tests/src/test/java/mediumtest/connection/OrganizationMediumTests.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotCheckStatusChangePermittedMediumTests.java
medium-tests/src/test/java/mediumtest/hotspots/HotspotStatusChangeMediumTests.java
medium-tests/src/test/java/mediumtest/http/SslMediumTests.java
medium-tests/src/test/java/mediumtest/http/TimeoutMediumTests.java
medium-tests/src/test/java/mediumtest/issues/CheckAnticipatedStatusChangeSupportedMediumTests.java
medium-tests/src/test/java/mediumtest/issues/CheckResolutionStatusChangePermittedMediumTests.java
medium-tests/src/test/java/mediumtest/issues/IssuesStatusChangeMediumTests.java
medium-tests/src/test/java/mediumtest/issues/OpenFixSuggestionInIdeMediumTests.java
medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java
medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java
medium-tests/src/test/java/mediumtest/rules/RuleDetailsMediumTests.java
medium-tests/src/test/java/mediumtest/server/events/ServerSentEventsMediumTests.java
medium-tests/src/test/java/mediumtest/smartnotifications/SmartNotificationsMediumTests.java
medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java
medium-tests/src/test/java/mediumtest/websockets/WebSocketMediumTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/initialize/SonarCloudAlternativeEnvironmentDto.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/initialize/SonarQubeCloudRegionDto.java
test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java

[SLCORE-1154](https://sonarsource.atlassian.net/browse/SLCORE-1154)
This extends the already existing alternative SonarQube Cloud environment (the EU region). This has to be implemented on the client side and can/will be re-used for the tests.
I think with that I found a good balance with not changing too much but relying on `DTO`s instead of adding just 3 more strings (`URI`s) to the `SonarCloudAlternativeEnvironmentDto`. The good thing is that the end user does not always have to have both `DTO`s or for one all `URI`s configured but can just change one specific for testing.
[SLCORE-1154]: https://sonarsource.atlassian.net/browse/SLCORE-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1154: Clients can specify an alternative US region environment

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingClueProvider.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/BindingClueProviderTests.java
medium-tests/src/test/java/mediumtest/SharedConnectedModeSettingsMediumTests.java
spec/connected_mode/binding_suggestion.adoc
test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java

[SLCORE-1157](https://sonarsource.atlassian.net/browse/SLCORE-1157)
When trying to guess binding clues, also take into account the region.
[SLCORE-1157]: https://sonarsource.atlassian.net/browse/SLCORE-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1157: Take into account SQ-C region for clues

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionManager.java
backend/core/src/main/java/org/sonarsource/sonarlint/core/connection/ServerConnection.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/ConnectionManagerTests.java
medium-tests/src/test/java/mediumtest/synchronization/ConnectionSyncMediumTests.java
medium-tests/src/test/java/mediumtest/taint/vulnerabilities/TaintVulnerabilitiesMediumTests.java
test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java

[SLCORE-1234](https://sonarsource.atlassian.net/browse/SLCORE-1234)
Solution is to introduce the cache of ServerConnection objects on the level of ConnectionManager. 
Getting connection without credentials is a creation of one-time use adhoc object to send a request that doesn't require authorization. So connections without credentials are not being stored in cache. And they never send connection error notifications. 
[SLCORE-1234]: https://sonarsource.atlassian.net/browse/SLCORE-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1234 Keep track of the connections state

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java
backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java
medium-tests/src/test/java/mediumtest/analysis/AnalysisCancellationMediumTests.java
medium-tests/src/test/java/mediumtest/analysis/sensor/WaitingCancellationSensor.java

[SLCORE-1077](https://sonarsource.atlassian.net/browse/SLCORE-1077)
[SLCORE-1077]: https://sonarsource.atlassian.net/browse/SLCORE-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1077 Cancel analysis when requested by the client

---

API_CHANGES.md
backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java
backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/TelemetryRpcServiceDelegate.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryAnalysisReportingCounter.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTests.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryMeasuresPayloadTests.java
medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/telemetry/TelemetryRpcService.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/AnalysisReportingTriggeredParams.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/AnalysisReportingType.java

[SLCORE-1276](https://sonarsource.atlassian.net/browse/SLCORE-1276)
The goal is to track the usage of specific types of analysis such as analysis VCS changed files, all project files, or the pre-commit analysis. Currently, these actions are purely triggered from the client side.
[SLCORE-1276]: https://sonarsource.atlassian.net/browse/SLCORE-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1276 Add telemetry metrics for usage of analysis reporting

---

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/BlameParser.java
backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/BlameParserTests.java

[SLCORE-1544](https://sonarsource.atlassian.net/browse/SLCORE-1544)
[SLCORE-1544]: https://sonarsource.atlassian.net/browse/SLCORE-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1544 Split porcelain output of `git blame` more robustly

---

backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/SonarCloudWebSocket.java
backend/core/src/test/java/org/sonarsource/sonarlint/core/websocket/SonarCloudWebSocketTests.java
backend/http/src/main/java/org/sonarsource/sonarlint/core/http/WebSocketClient.java
backend/http/src/test/java/org/sonarsource/sonarlint/core/http/WebSocketClientTest.java
medium-tests/src/test/java/mediumtest/websockets/WebSocketMediumTests.java

[SLCORE-1198](https://sonarsource.atlassian.net/browse/SLCORE-1198)
Errors with most event from Sentry and with no utility:
```
java.io.IOException: closed output
[...]
at org.sonarsource.sonarlint.core.websocket.SonarCloudWebSocket.close(SonarCloudWebSocket.java:207)
```
```
java.nio.channels.UnresolvedAddressException: null
[...]
at org.sonarsource.sonarlint.core.websocket.SonarCloudWebSocket.close(SonarCloudWebSocket.java:190)
```
[SLCORE-1198]: https://sonarsource.atlassian.net/browse/SLCORE-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1198 Avoid noisy logs with WebSocket

---

.cirrus.yml
README.md

[SLCORE-1584](https://sonarsource.atlassian.net/browse/SLCORE-1584)
[SLCORE-1584]: https://sonarsource.atlassian.net/browse/SLCORE-1584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1584 Update GitHub repo description

---

medium-tests/src/test/java/mediumtest/BindingSuggestionsMediumTests.java
medium-tests/src/test/java/mediumtest/SonarLintTestHarnessMediumTests.java
test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java

[SLCORE-1550](https://sonarsource.atlassian.net/browse/SLCORE-1550)
[SLCORE-1550]: https://sonarsource.atlassian.net/browse/SLCORE-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1550 Use ServerFixture for BindingSuggestionsMediumTests

---

.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/slack_notify.yml

[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …

BUILD-8875: Migrate to standardized GitHub runner names

---

API_CHANGES.md
backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java
backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/TelemetryRpcServiceDelegate.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java
backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorageTests.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTests.java
backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryMeasuresPayloadTests.java
medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java
rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/telemetry/TelemetryRpcService.java

[SLCORE-1655](https://sonarsource.atlassian.net/browse/SLCORE-1655)
We should track if SQ:IDE integration was enabled at least once during the day, when SonarQube MCP Server is starting.
Measure: mcp.integration_enabled → false/true
It resets to false every day
[SLCORE-1655]: https://sonarsource.atlassian.net/browse/SLCORE-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLCORE-1655 Telemetry for MCP integration
