client-api/pom.xml, client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/TextSearchIndex.java, client-api/src/test/java/org/sonarsource/sonarlint/core/client/api/TextSearchIndexTest.java
Maybe create a package for this kind of utility libs?
I can add tests for more situations once we know about them.
=> Lib to search text using indexes

core/src/main/java/org/sonarsource/sonarlint/core/container/storage/SonarQubeActiveRulesProvider.java, its/projects/sample-java/src/main/java/foo/Foo.java, its/src/test/java/its/ConnectedModeTest.java
=> SLCORE-48 Rules created from templates don't raise issues

core/pom.xml, core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginClassloaderFactory.java, core/src/test/java/org/sonarsource/sonarlint/core/mediumtest/StandaloneIssueMediumTest.java, core/src/test/java/org/sonarsource/sonarlint/core/util/PluginLocator.java
Add missing woodstox dependency
=> SLCORE-56 Support Python analyzer 1.6

client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/common/RuleDetails.java, core/src/main/java/org/sonarsource/sonarlint/core/container/connected/update/RulesDownloader.java, core/src/main/java/org/sonarsource/sonarlint/core/container/global/DefaultRuleDetails.java, core/src/main/java/org/sonarsource/sonarlint/core/container/standalone/StandaloneGlobalContainer.java, core/src/main/java/org/sonarsource/sonarlint/core/container/storage/StorageGlobalContainer.java, core/src/main/protobuf/sonarlint.proto, core/src/test/java/org/sonarsource/sonarlint/core/container/connected/update/RulesDownloaderTest.java, its/src/test/java/its/ConnectedModeTest.java
If you're ok to merge, let me know and I'll squash
=> SLCORE-59 Get extended rule description from server

appveyor.yml, client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/util/FileUtils.java, core/src/main/java/org/sonarsource/sonarlint/core/container/connected/update/ModuleHierarchyDownloader.java, core/src/test/java/org/sonarsource/sonarlint/core/container/analysis/filesystem/DefaultFilePredicatesTest.java, core/src/test/java/org/sonarsource/sonarlint/core/container/analysis/filesystem/InputFileBuilderTest.java, core/src/test/java/org/sonarsource/sonarlint/core/container/analysis/filesystem/SonarLintInputDirTest.java, core/src/test/java/org/sonarsource/sonarlint/core/container/analysis/filesystem/SonarLintInputFileTest.java, core/src/test/java/org/sonarsource/sonarlint/core/container/connected/ServerIssueStoreTest.java, core/src/test/java/org/sonarsource/sonarlint/core/util/LoggedErrorHandlerTest.java, pom.xml
Also fix all unit test failures in Windows.
=> SLI-130 fix module key of nested projects in windows

client-api/pom.xml, client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/util/FileUtils.java, client-api/src/test/java/org/sonarsource/sonarlint/core/client/api/util/FileUtilsTest.java, core/pom.xml, core/src/test/java/org/sonarsource/sonarlint/core/analyzer/sensor/SensorsExecutorTest.java, core/src/test/java/org/sonarsource/sonarlint/core/container/connected/update/check/ModuleStorageUpdateCheckerTest.java, core/src/test/java/org/sonarsource/sonarlint/core/container/storage/IssueStoreReaderTest.java, pom.xml
And also updated to mockito 2.x
=> SLCORE-97 Fallback on non atomic move when creating storage

client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/util/TextSearchIndex.java, client-api/src/test/java/org/sonarsource/sonarlint/core/client/api/util/TextSearchIndexTest.java
Sorting by text when scores are the same or too low should be done by the caller.
=> Improve text search

core/pom.xml, core/src/main/java/org/sonarsource/sonarlint/core/analyzer/issue/DefaultFilterableIssue.java, core/src/main/java/org/sonarsource/sonarlint/core/analyzer/sensor/DefaultSensorContext.java, core/src/main/java/org/sonarsource/sonarlint/core/analyzer/sensor/DefaultSensorStorage.java, core/src/main/java/org/sonarsource/sonarlint/core/analyzer/sensor/noop/NoOpNewExternalIssue.java, core/src/main/java/org/sonarsource/sonarlint/core/analyzer/sensor/noop/NoOpNewIssueLocation.java, core/src/main/java/org/sonarsource/sonarlint/core/analyzer/sensor/noop/NoOpNewSignificantCode.java, core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginCacheLoader.java, core/src/test/java/org/sonarsource/sonarlint/core/analyzer/sensor/DefaultSensorContextTest.java, pom.xml
Also update Maven plugins and other "small" dependencies
=> SLCORE-203 Update to SQ Plugin API 7.2

core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginCacheLoader.java
=> SLCORE-217 Update scala analyzer key

core/pom.xml
=> Update core/pom.xml gson 2.8.4 to 2.8.5

core/src/main/java/com/sonarsource/plugins/license/api/LicensedPluginRegistration.java, core/src/main/java/com/sonarsource/plugins/license/api/package-info.java, core/src/main/java/org/sonarsource/sonarlint/core/container/analysis/MutableAnalysisSettings.java, core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginClassloaderFactory.java, daemon/pom.xml, its/tests/projects/sample-c/src/file.c, its/tests/src/test/java/its/StandaloneDaemonTest.java
=> SLCORE-230 Update CFamily plugin in the daemon

client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/util/FileUtils.java, client-api/src/test/java/org/sonarsource/sonarlint/core/client/api/util/FileUtilsTest.java, language-server/pom.xml, language-server/src/main/java/org/sonarlint/languageserver/ServerInfoCache.java, language-server/src/main/java/org/sonarlint/languageserver/SonarLintLanguageServer.java, language-server/src/test/java/org/sonarlint/languageserver/SonarLintLanguageServerTest.java
Related to [SLVSCODE-47](https://jira.sonarsource.com/projects/SLVSCODE/issues/SLVSCODE-47).
=> SLCORE-232 Fix issue tracking on subfolders

its/tests/src/test/java/its/OrganizationTest.java
* Upgrade project api usage in Organization ITs
=> Upgrade project api usage in ITs

language-server/src/main/java/org/sonarlint/languageserver/SonarLintLanguageServer.java, language-server/src/test/java/org/sonarlint/languageserver/SonarLintLanguageServerTest.java
First attempt at auto-refresh of analyzed files on configuration change: have the IDE send a custom request with all open files.
=> SLCORE-244 Add custom command to refresh diagnostics

core/src/main/java/org/sonarsource/sonarlint/core/container/analysis/MutableAnalysisSettings.java, core/src/test/java/org/sonarsource/sonarlint/core/mediumtest/StandaloneIssueMediumTest.java
=> SLCORE-250 Fix properties inheritance

core/src/main/java/org/sonarsource/sonarlint/core/tracking/IndexedObjectStore.java, core/src/main/java/org/sonarsource/sonarlint/core/tracking/IssueStore.java, core/src/main/java/org/sonarsource/sonarlint/core/tracking/PersistentIssueTrackerCache.java, core/src/main/java/org/sonarsource/sonarlint/core/tracking/ServerIssueTracker.java, core/src/test/java/org/sonarsource/sonarlint/core/tracking/IndexedObjectStoreTest.java, core/src/test/java/org/sonarsource/sonarlint/core/tracking/IssueStoreTest.java, core/src/test/java/org/sonarsource/sonarlint/core/tracking/PersistentIssueTrackerCacheTest.java, core/src/test/java/org/sonarsource/sonarlint/core/tracking/ServerIssueTrackerTest.java, language-server/src/main/java/org/sonarlint/languageserver/ConnectedEngineFactory.java, language-server/src/main/java/org/sonarlint/languageserver/ServerInfoCache.java, language-server/src/main/java/org/sonarlint/languageserver/ServerIssueTracker.java, language-server/src/main/java/org/sonarlint/languageserver/SonarLintExtendedLanguageClient.java, language-server/src/main/java/org/sonarlint/languageserver/SonarLintExtendedLanguageServer.java, language-server/src/main/java/org/sonarlint/languageserver/SonarLintLanguageServer.java, language-server/src/main/java/org/sonarlint/languageserver/StandaloneEngineFactory.java, language-server/src/main/java/org/sonarlint/languageserver/log/ClientLogger.java, language-server/src/main/java/org/sonarlint/languageserver/log/DefaultClientLogger.java, language-server/src/main/java/org/sonarlint/languageserver/log/LanguageClientLogOutput.java, language-server/src/main/java/org/sonarlint/languageserver/log/package-info.java, language-server/src/test/java/org/sonarlint/languageserver/ConnectedEngineFactoryTest.java, language-server/src/test/java/org/sonarlint/languageserver/ServerIssueTrackerTest.java, language-server/src/test/java/org/sonarlint/languageserver/ServerMainTest.java, language-server/src/test/java/org/sonarlint/languageserver/SonarLintLanguageServerTest.java, language-server/src/test/java/org/sonarlint/languageserver/log/DefaultClientLoggerTest.java, language-server/src/test/java/org/sonarlint/languageserver/log/LanguageClientLogOutputTest.java
* delete specific logging facade for issue tracking
* handle vscode specific $/setTraceNotification
=> Rework logging

README.md, language-server/src/main/java/org/sonarlint/languageserver/SonarLintLanguageServer.java, language-server/src/main/java/org/sonarlint/languageserver/folders/WorkspaceFolderWrapper.java, language-server/src/main/java/org/sonarlint/languageserver/folders/WorkspaceFoldersManager.java, language-server/src/main/java/org/sonarlint/languageserver/folders/package-info.java, language-server/src/test/java/org/sonarlint/languageserver/SonarLintLanguageServerTest.java, language-server/src/test/java/org/sonarlint/languageserver/folders/WorkspaceFoldersManagerTest.java
@jblievremont Only look at the second commit, the first one is already in the other PR
=> Workspace manager

core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryClient.java, core/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryClientTest.java
... Unless internal debug is enabled
=> SLCORE-268 Make sure telemetry is completely silent

client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/common/Language.java, client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/common/PluginDetails.java, client-api/src/main/java/org/sonarsource/sonarlint/core/client/api/common/SkipReason.java, client-api/src/test/java/org/sonarsource/sonarlint/core/client/api/common/SkipReasonTests.java, core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginInfosLoader.java, core/src/test/java/org/sonarsource/sonarlint/core/plugin/PluginInfosLoaderTests.java, its/tests/src/test/java/its/ConnectedModeRequirementsTest.java
I discovered that plugins with multiple languages are not correctly handled.
=> SLCORE-271 Handle properly plugins with multiple languages

its/tests/pom.xml, its/tests/src/test/java/its/AbstractConnectedTest.java, its/tests/src/test/java/its/CommercialAnalyzerTest.java, its/tests/src/test/java/its/ConnectedFileMatchingTest.java, its/tests/src/test/java/its/ConnectedModeExcludeByVersionTest.java, its/tests/src/test/java/its/ConnectedModeRequirementsTest.java, its/tests/src/test/java/its/ConnectedModeTest.java
This is to fix failure on the dogfood axis of QA.
=> Update Orchestrator to support SonarQube 8.5

core/src/main/java/org/sonarsource/sonarlint/core/container/analysis/MutableAnalysisSettings.java
=> remove eclipse specific case from the core

core/pom.xml, core/src/main/java/org/sonarsource/sonarlint/core/container/analysis/filesystem/LanguageDetection.java, core/src/test/java/org/sonarsource/sonarlint/core/mediumtest/StandaloneIssueMediumTests.java, core/src/test/java/org/sonarsource/sonarlint/core/util/PluginLocator.java, its/tests/src/test/java/its/CommercialAnalyzerTest.java, its/tests/src/test/java/its/tools/ItUtils.java
Also test the new way of passing the build wrapper configuration
=> Update CFamily analyzer in tests

core/src/main/java/org/sonarsource/sonarlint/core/client/api/common/Language.java
=> SLCORE-314 support secrets plugin and secrets language

core/src/main/java/org/sonarsource/sonarlint/core/client/api/connected/ConnectedGlobalConfiguration.java, core/src/main/java/org/sonarsource/sonarlint/core/container/storage/SonarQubeActiveRulesProvider.java, core/src/main/java/org/sonarsource/sonarlint/core/container/storage/StorageContainer.java, core/src/main/java/org/sonarsource/sonarlint/core/container/storage/StoragePluginIndexProvider.java, core/src/main/java/org/sonarsource/sonarlint/core/container/storage/StorageReader.java, core/src/test/java/org/sonarsource/sonarlint/core/mediumtest/ConnectedExtraPluginMediumTest.java
=> SLCORE-326 Allow embedded plugins working in connected mode

core/src/test/java/org/sonarsource/sonarlint/core/AbstractSonarLintEngineTests.java
=> fix compilation error in AbstractSonarLintEngineTests

core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryClientAttributesProvider.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManager.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryPayload.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryRulesPayload.java, core/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTest.java, core/src/test/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryPayloadTest.java
=> SLCORE-311 telemetry for secrets

core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManager.java, core/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTest.java
=> performance optimization for rules telemetry

its/tests/src/test/java/its/CommercialAnalyzerTest.java, its/tests/src/test/java/its/ConnectedFileMatchingTest.java, its/tests/src/test/java/its/ConnectedModeRequirementsTest.java, its/tests/src/test/java/its/ConnectedModeTest.java, its/tests/src/test/java/its/tools/ItUtils.java
SonarQube embeds all plugins since 7.9, so we can rely on bundled plugins.
=> Simplify IT matrix

core/src/main/java/org/sonarsource/sonarlint/core/tracking/IssueTrackable.java, core/src/main/java/org/sonarsource/sonarlint/core/tracking/ProtobufIssueStore.java, core/src/main/java/org/sonarsource/sonarlint/core/tracking/ProtobufIssueTrackable.java, core/src/main/java/org/sonarsource/sonarlint/core/tracking/ServerIssueTrackable.java, core/src/test/java/org/sonarsource/sonarlint/core/tracking/IssueTrackableTest.java, issue-tracking/src/main/java/org/sonarsource/sonarlint/core/issuetracking/AbstractTrackable.java, issue-tracking/src/main/java/org/sonarsource/sonarlint/core/issuetracking/InMemoryIssueTrackerCache.java, issue-tracking/src/main/java/org/sonarsource/sonarlint/core/issuetracking/IssueTrackerCache.java, issue-tracking/src/main/java/org/sonarsource/sonarlint/core/issuetracking/PersistentIssueTrackerCache.java, issue-tracking/src/main/java/org/sonarsource/sonarlint/core/issuetracking/Trackable.java, issue-tracking/src/main/java/org/sonarsource/sonarlint/core/issuetracking/TrackableIssueStore.java, issue-tracking/src/test/java/org/sonarsource/sonarlint/core/issuetracking/IssueTrackerTests.java, issue-tracking/src/test/java/org/sonarsource/sonarlint/core/issuetracking/PersistentIssueTrackerCacheTests.java
=> Restore a client object field on Trackable

its/tests/pom.xml, its/tests/src/test/java/its/ConnectedCommunityIssueDownloadTest.java, its/tests/src/test/java/its/ConnectedDeveloperIssueDownloadTest.java, its/tests/src/test/java/its/ConnectedFileMatchingTest.java, its/tests/src/test/java/its/ConnectedModeSynchronizationTest.java, its/tests/src/test/java/its/ConnectedModeTest.java, server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/issue/IssueApi.java, server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerIssueUpdater.java
This PR should pass to green once bugs are fixed on SQ side.
=> Issue pull only in SQ 9.6+

its/tests/src/test/java/its/AbstractConnectedTest.java, its/tests/src/test/java/its/CommercialAnalyzerTest.java, its/tests/src/test/java/its/ConnectedCommunityIssueDownloadTest.java, its/tests/src/test/java/its/ConnectedDeveloperIssueDownloadTest.java, its/tests/src/test/java/its/ConnectedEmbeddedPluginTest.java, its/tests/src/test/java/its/ConnectedFileMatchingTest.java, its/tests/src/test/java/its/ConnectedModeRequirementsTest.java, its/tests/src/test/java/its/ConnectedModeSynchronizationTest.java, its/tests/src/test/java/its/ConnectedModeTest.java, its/tests/src/test/java/its/ConnectedTaintVulnerabilitiesTest.java, its/tests/src/test/java/its/SonarCloudTest.java
After SONAR-17524, the default main branch name is "main". To simplify our tests on different versions, we will revert to "master".
=> Fix QA with SQ 9.8

azure-pipelines.yml
Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-core/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:
=> BUILD-2010 sonarlint creds

server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java
I don't see how I can test that...
=> SLCORE-428 Allow Xodus to start on removable/remote/ramdisk FS

azure-pipelines.yml, core/src/main/java/org/sonarsource/sonarlint/core/smartnotifications/SmartNotifications.java, core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationServiceImpl.java, core/src/test/java/mediumtest/StandaloneIssueMediumTests.java, core/src/test/java/mediumtest/StandaloneNodeJsTests.java, core/src/test/java/testutils/ConsoleConsumer.java, its/tests/src/test/java/its/SonarQubeCommunityEditionTests.java, its/tests/src/test/java/its/utils/ConsoleConsumer.java, pom.xml, report-aggregate/pom.xml, server-api/pom.xml, server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/stream/EventStream.java
* Update surefire plugin
* More reliable close of executor services
* Update JDK used to run tests with coverage
=> Try different ideas to solve coverage drop

core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetailsAdapter.java, core/src/test/java/mediumtest/EffectiveRulesMediumTests.java
=> SLCORE-472 remove empty lines from clean code principles page

core/pom.xml, core/src/main/java/org/sonarsource/sonarlint/core/InitializedSonarLintBackend.java, core/src/main/java/org/sonarsource/sonarlint/core/http/ClientProxySelector.java, core/src/main/java/org/sonarsource/sonarlint/core/http/HttpClientManager.java, core/src/test/java/mediumtest/AuthenticationMediumTests.java, core/src/test/java/mediumtest/HttpClientManagerMediumTests.java, core/src/test/java/mediumtest/ProxyMediumTests.java, core/src/test/java/mediumtest/SslMediumTests.java, core/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java, core/src/test/java/org/sonarsource/sonarlint/core/http/HttpClientManagerTests.java, core/src/test/java/testutils/TestUtils.java
Sorry, I think I messed up with my previous PR, you might have already reviewed the first 2 commits.
=> First steps for SSL support

core/src/main/java/org/sonarsource/sonarlint/core/http/AskClientCertificatePredicate.java, http/src/main/java/org/sonarsource/sonarlint/core/http/HttpClientProvider.java, pom.xml
Internal PR from #633 to trigger a full pipeline
=> Bump sslcontext-kickstart to version 8.1.2

.cirrus.yml, wss-unified-agent.config
Fix build conditions [BUILD-3317](https://sonarsource.atlassian.net/browse/BUILD-3317)
[BUILD-3317]: https://sonarsource.atlassian.net/browse/BUILD-3317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-3317 fix build conditions

commons/src/main/java/org/sonarsource/sonarlint/core/commons/log/LogOutputDelegator.java
Waiting for completely reworking logs, I think this workaround could already improve the situation
=> SLCORE-510 Quick and dirty fix for lost logs

.cirrus.yml
Following https://sonarsource.atlassian.net/browse/BUILD-3483?focusedCommentId=513295 comment because same issue happened
=> Increase CIRRUS_CLONE_DEPTH to 50

core/src/test/java/mediumtest/http/ProxyMediumTests.java
=> SLCORE-530 Medium test for proxy outside valid port range

client-api/src/main/java/org/sonarsource/sonarlint/core/clientapi/client/issue/ShowIssueParams.java, core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java, medium-tests/src/test/java/mediumtest/issues/ShowIssueMediumTests.java
When opening an issue in IDE we also want to know the branch and possibly pull request information. Checking against the branch is part of the MMF for Eclipse and with these changes, it can also be added to SLI / SLVSCODE in retrospect.
There are no real changes only the `branch` and `pullRequest` parameters from the methods are now passed down to `ShowIssueParams`.
=> SLCORE-614: Open issue in IDE with branch / PR

core/src/main/java/org/sonarsource/sonarlint/core/http/ConnectionAwareHttpClientProvider.java, core/src/main/java/org/sonarsource/sonarlint/core/websocket/SonarCloudWebSocket.java, http/src/main/java/org/sonarsource/sonarlint/core/http/WebSocketClient.java, medium-tests/src/test/java/mediumtest/fixtures/SonarLintTestRpcServer.java, medium-tests/src/test/java/mediumtest/websockets/WebSocketMediumTests.java, medium-tests/src/test/java/testutils/JuliSLF4JDelegatingLog.java, medium-tests/src/test/resources/META-INF/services/org.apache.juli.logging.Log, medium-tests/src/test/resources/simplelogger.properties, rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/SonarLintRpcServerImpl.java
This is fixing a thread leak in the WebSocket part.
Medium tests before:
After:
=> Medium test performance fixes

core/src/main/java/org/sonarsource/sonarlint/core/ConnectedSonarLintEngineImpl.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcClient.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/ClientErrorCode.java
Feedback from @eray-felek-sonarsource
=> RPC feedback

backend-cli/pom.xml
Automatically enable profiles based on os to build its artifacts
=> Automatically enable profiles based on os to build its artifacts

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLiveAttributes.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManager.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryServerConstantAttributes.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryServerLiveAttributes.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTests.java, core/src/main/java/org/sonarsource/sonarlint/core/NodeJsHelper.java, core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryServerAttributesProvider.java, core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, core/src/test/java/org/sonarsource/sonarlint/core/TelemetryServerAttributesProviderTests.java, its/tests/src/test/java/its/AbstractConnectedTests.java, its/tests/src/test/java/its/SloopLauncherTests.java, its/tests/src/test/java/its/SloopLauncherWithJreTests.java, medium-tests/src/test/java/mediumtest/InitializationMediumTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java, medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryClientConstantAttributesDto.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryClientLiveAttributesResponse.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/TelemetryServerConstantAttributesDto.java
Don't ask about
- platform
- architecture
- NodeJs version
BugFix:  make sure to send constantAdditionalAttributes with liveAdditionalAttributes
=> SLCORE-629   Slim down TelemetryConstantAttributes and don't ask client for info we can infer on the backend

its/tests/src/test/java/its/SonarCloudTests.java
The test was added with #832 but turned out to be too flaky.
=> NO-JIRA: Remove flaky integration test

backend/core/src/main/java/org/sonarsource/sonarlint/core/commons/SmartCancelableLoadingCache.java
I can reproduce using a debugger to force a certain execution order, but not easy to write a unit test. It was failing randomly on CI.
=> SLCORE-683 Fix race condition in the SmartCancellableLoadingCache

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/api/SonarLanguage.java
I was asked if this was already done and I noticed that I forgot about it. The impact should be low.
=> SLCORE-649: RPG suffix property

client/java-client-utils/src/main/java/org/sonarsource/sonarlint/core/client/utils/IssueResolutionStatus.java
=> SLCORE-692: Rephrase the wording on the "Mark issues as..." action

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/payload/IssuePayload.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorageManagerTests.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryPayloadTests.java
=> SLCORE-720 add back issue_status_changed_count to telemetry

its/tests/pom.xml, its/tests/src/test/java/its/SonarCloudTests.java, its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java, its/tests/src/test/java/its/utils/PluginLocator.java, medium-tests/src/test/java/mediumtest/file/ConnectedFileExclusionsMediumTests.java
This makes the test faster as we don't need to sync the plugin
=> Use embedded JS plugin for ITs

backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/RuleSetChangedEventParser.java
See https://sonarsource.atlassian.net/browse/SLCORE-664?focusedCommentId=596799
=> SLCORE-664 Protect from nulls in RuleSetChangedEvent

.sonarlint/connectedMode.json
Share the information for SLCORE amongst contributors! :smile:
=> NO-JIRA: Shared Connected Mode configuration

docs/PULL_REQUEST_TEMPLATE.md
=> SLCORE-768 Draft a PR template

API_CHANGES.md, backend/analysis-engine/pom.xml, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisResults.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/RawIssue.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/analysis/AnalyzeFilesResponse.java
=> SLCORE-797 Return the list of raw issues in AnalyzeFilesResponse

backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/PluginsStorage.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizerTests.java, medium-tests/src/test/java/mediumtest/synchronization/PluginSynchronizationMediumTests.java
=> SLCORE-808 Create default plugin storage file if no plugin to download

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/NodeJsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryServerAttributesProvider.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/TelemetryServerAttributesProviderTests.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/PluginsLoader.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/loading/SonarPluginRequirementsChecker.java, backend/plugin-commons/src/test/java/org/sonarsource/sonarlint/core/plugin/commons/loading/SonarPluginRequirementsCheckerTests.java, medium-tests/src/test/java/mediumtest/analysis/NodeJsMediumTests.java
Blocked while discussing this functional change with the team
=> SLCORE-789 Skip loading SonarJS if no Node.js configured

pom.xml
=> NO_JIRA: Update parent pom

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-legacy/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, rule-extractor-cli/pom.xml
Update pom versions to `10.3-SNAPSHOT`
=> Prepare for next development iteration

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisResults.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisResultsTest.java
=> SLCORE-822 set emptyList to rawIssues as an initial value

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingCandidatesFinder.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/TextSearchIndex.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowHotspotRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/TextSearchIndexTest.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandlerTests.java, medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/adapter/EitherSonarQubeSonarCloudConnectionParamsAdapterFactory.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/AssistCreatingConnectionParams.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/SonarCloudConnectionParams.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/SonarQubeConnectionParams.java
=> SLCORE-804 Open an issue in the IDE from SonarCloud

backend/core/src/main/java/org/sonarsource/sonarlint/core/TokenGeneratorHelper.java, medium-tests/src/test/java/mediumtest/ConnectionSetupMediumTests.java
=> SLCORE-843 add SonarCloud support for generating token

backend/commons/src/main/resources/logback-shared.xml
=> SLCORE-851 Disable noisy org.eclipse.jgit debug logs

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/fs/FileExclusionService.java, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientImpl.java, medium-tests/src/test/java/mediumtest/file/ClientFileExclusionsMediumTests.java, medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcClient.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/analysis/GetFileExclusionsParams.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/analysis/GetFileExclusionsResponse.java
validated in IntelliJ. IntelliJ test branch: poc/serhat/client-file-exclusions
=> SLCORE-826 Let clients provide user-configured local file exclusions

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/GitBlameUtils.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/SonarLintBlameResult.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitBlameUtilsTest.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/SonarLintBlameResultTest.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/testutils/GitUtils.java
=> SLCORE-863 Fix git blame subfolder issue

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/log/LogOutput.java, backend/slf4j-sonar-log/pom.xml, backend/slf4j-sonar-log/src/main/java/org/slf4j/LoggerAdapter.java, backend/slf4j-sonar-log/src/main/java/org/slf4j/LoggerFactory.java, backend/slf4j-sonar-log/src/test/java/org/slf4j/LoggerAdapterTest.java, backend/slf4j-sonar-log/src/test/java/org/slf4j/LoggerFactoryTest.java, report-aggregate/pom.xml
=> SLCORE-853 kill noisy com.networknt.schema logs

medium-tests/src/test/java/mediumtest/tracking/IssueStreamingSensor.java, medium-tests/src/test/java/testutils/plugins/src/DefaultRulesDefinition.java, medium-tests/src/test/java/testutils/plugins/src/DefaultSensor.java
=> NO_JIRA: Fix issues reported by rules newly enabled on test sources

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/gitblame/GitBlameUtils.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/gitblame/GitRepoNotFoundException.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitBlameUtilsTest.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/SonarLintBlameResultTest.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java, medium-tests/src/test/java/mediumtest/fixtures/ClientLogFixtures.java, medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java
=> SLCORE-859 Give clients a precise message in case base dir is not in the git repo

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/gitblame/package-info.java
=> NO-JIRA: Fix SQ analysis (missing package-info.java)

pom.xml
=> NO-JIRA: Update parent pom

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-legacy/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, rule-extractor-cli/pom.xml
=> NO-JIRA: Prepare for next development iteration

backend/commons/src/main/resources/logback-shared.xml
=> SLCORE-881 Disable noisy org.sonar.scm.git.blame debug logs

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/NewRulesActivatedOnServer.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java
=> SLCORE-829 Trigger new analysis on  RuleSetChangedEvent

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/StandaloneRulesConfigurationChanged.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java, medium-tests/src/test/java/mediumtest/file/ClientFileExclusionsMediumTests.java, medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java
=> SLCORE-884 Trigger a new reporting when new rules are disabled in Standalone mode

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisReadinessMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java
=> SLCORE-887 Trigger an analysis on open files when it becomes ready

.cirrus.yml
With EOL of 31st of July, rather getting rid of Burgr early.
=> SLCORE-885: Drop Burgr in Cirrus CI

backend/core/src/main/java/org/sonarsource/sonarlint/core/branch/SonarProjectBranchTrackingService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandler.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandlerTests.java
=> SLCORE-909 check if branches match during open fix in IDE

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisTriggeringMediumTests.java
I decided to just ignore symlink URIs as a fix. Resolving symlink URIs to real links turned out to be a bit more involved than I expected. A summary of findings is documented in the new improvement ticket:
https://sonarsource.atlassian.net/browse/SLCORE-925
=> SLCORE-920 Windows symbolic links are not supported

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/GitUtilsTest.java
[SLCORE-927](https://sonarsource.atlassian.net/browse/SLCORE-927)
[SLCORE-927]: https://sonarsource.atlassian.net/browse/SLCORE-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-927 read gitignore from bare repos too

pom.xml
[SLCORE-932](https://sonarsource.atlassian.net/browse/SLCORE-932)
[SLCORE-932]: https://sonarsource.atlassian.net/browse/SLCORE-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-932 NO-JIRA: Update parent POM

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-legacy/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-936](https://sonarsource.atlassian.net/browse/SLCORE-936)
[SLCORE-936]: https://sonarsource.atlassian.net/browse/SLCORE-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-936 Prepare for next development iteration

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientImpl.java, its/tests/src/test/java/its/MockSonarLintRpcClientDelegate.java, medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java, medium-tests/src/test/java/mediumtest/issues/OpenFixSuggestionInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/sloop/SloopLauncherTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/binding/NoBindingSuggestionFoundParams.java
[SLCORE-924](https://sonarsource.atlassian.net/browse/SLCORE-924)
When no binding suggestion was found, the response that will be handled by the IDE will contain the information whether it was for a SonarCloud connection or not.
[SLCORE-924]: https://sonarsource.atlassian.net/browse/SLCORE-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-924: No binding suggestion with SQ/SC info

.github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml
[SLCORE-951](https://sonarsource.atlassian.net/browse/SLCORE-951)
[SLCORE-951]: https://sonarsource.atlassian.net/browse/SLCORE-951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-951 Jira integration: Use repo vault token

backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/SonarCloudWebSocket.java
[SLCORE-878](https://sonarsource.atlassian.net/browse/SLCORE-878)
When in Connected Mode to SonarCloud, every now and then, the Web Socket is closed, and every time, there is an error in the logs. This is misleading as the error message states that the connection was just closed, and nothing else happened.
On Eclipse, for example, the SonarLint Console is triggered (like for every other error) and brought to the front. This is distracting and as the error message is incorrect, this is misleading.
[SLCORE-878]: https://sonarsource.atlassian.net/browse/SLCORE-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-878: Remove misleading error log

API_CHANGES.md, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SloopLauncher.java, client/rpc-java-client/src/test/java/org/sonarsource/sonarlint/core/rpc/client/SloopLauncherTests.java
[SLCORE-947](https://sonarsource.atlassian.net/browse/SLCORE-947)
[SLCORE-947]: https://sonarsource.atlassian.net/browse/SLCORE-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-947 Allow to tune the JVM

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-legacy/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-953](https://sonarsource.atlassian.net/browse/SLCORE-953)
[SLCORE-953]: https://sonarsource.atlassian.net/browse/SLCORE-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-953 Prepare for next development iteration

pom.xml
[SLCORE-934](https://sonarsource.atlassian.net/browse/SLCORE-934)
[SLCORE-934]: https://sonarsource.atlassian.net/browse/SLCORE-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-934 Update spring version

pom.xml
[SLCORE-952](https://sonarsource.atlassian.net/browse/SLCORE-952)
[SLCORE-952]: https://sonarsource.atlassian.net/browse/SLCORE-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-952 Update protobuf version

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingClueProvider.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/ServerApiProvider.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/ServerApiProviderTests.java
[SLCORE-880](https://sonarsource.atlassian.net/browse/SLCORE-880)
[SLCORE-880]: https://sonarsource.atlassian.net/browse/SLCORE-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-880 SonarCloud alternative environment with trailing backslash

API_CHANGES.md, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientImpl.java, medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/hotspot/RaiseHotspotsParams.java
[SLCORE-850](https://sonarsource.atlassian.net/browse/SLCORE-850)
[SLCORE-850]: https://sonarsource.atlassian.net/browse/SLCORE-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-850 Rename the RaiseHotspotsParams.issuesByFileUri parameter

backend/core/src/main/java/org/sonarsource/sonarlint/core/reporting/FindingReportingService.java
[SLCORE-954](https://sonarsource.atlassian.net/browse/SLCORE-954)
[SLCORE-954]: https://sonarsource.atlassian.net/browse/SLCORE-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-954 Avoid sending duplicated issues

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/NodeJsService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java, medium-tests/src/test/java/mediumtest/analysis/NodeJsMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/analysis/AnalysisRpcService.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/analysis/GetForcedNodeJsResponse.java
[SLCORE-815](https://sonarsource.atlassian.net/browse/SLCORE-815)
[SLCORE-815]: https://sonarsource.atlassian.net/browse/SLCORE-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-815 Return Node.js details to the client

API_CHANGES.md, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisConfiguration.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisConfigurationTests.java
[SLCORE-956](https://sonarsource.atlassian.net/browse/SLCORE-956)
[SLCORE-956]: https://sonarsource.atlassian.net/browse/SLCORE-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-956 Remove unnecessary log information about active rules

pom.xml
[SLCORE-971](https://sonarsource.atlassian.net/browse/SLCORE-971)
[SLCORE-971]: https://sonarsource.atlassian.net/browse/SLCORE-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-971 Update parent POM to 78.0.0.2155

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-legacy/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-973](https://sonarsource.atlassian.net/browse/SLCORE-973)
[SLCORE-973]: https://sonarsource.atlassian.net/browse/SLCORE-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-973 Prepare for next development iteration

client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml
[BUILD-6535](https://sonarsource.atlassian.net/browse/BUILD-6535)
[BUILD-6535]: https://sonarsource.atlassian.net/browse/BUILD-6535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-6535 no javadoc jar found

its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
[SLCORE-1001](https://sonarsource.atlassian.net/browse/SLCORE-1001)
[SLCORE-1001]: https://sonarsource.atlassian.net/browse/SLCORE-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1001 Fix override of taint vulnerability impact severity in SQ 10.8+

backend/core/src/main/java/org/sonarsource/sonarlint/core/repository/rules/RulesRepository.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/rules/RulesServiceTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java
[SLCORE-979](https://sonarsource.atlassian.net/browse/SLCORE-979)
[SLCORE-979]: https://sonarsource.atlassian.net/browse/SLCORE-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-979 Avoid keeping track of non-useful data - rules data

pom.xml
[SLCORE-1005](https://sonarsource.atlassian.net/browse/SLCORE-1005)
[SLCORE-1005]: https://sonarsource.atlassian.net/browse/SLCORE-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1005 Update parent pom to 80.0.0.2205

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-legacy/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1006](https://sonarsource.atlassian.net/browse/SLCORE-1006)
[SLCORE-1006]: https://sonarsource.atlassian.net/browse/SLCORE-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1006 Prepare for next development iteration

backend/core/src/main/java/org/sonarsource/sonarlint/core/VersionSoonUnsupportedHelper.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/hotspot/HotspotService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/settings/SettingsApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/system/ServerStatusInfo.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/system/SystemApi.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/settings/SettingsApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerConnection.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerInfoSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerPathProvider.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerVersionAndStatusChecker.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/StoredServerInfo.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ServerInfoStorage.java, backend/server-connection/src/main/proto/sonarlint.proto, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/ServerInfoSynchronizerTests.java, medium-tests/src/test/java/mediumtest/fixtures/ServerFixture.java, medium-tests/src/test/java/mediumtest/synchronization/ServerInfoSynchronizationMediumTests.java
[SLCORE-991](https://sonarsource.atlassian.net/browse/SLCORE-991)
[SLCORE-991]: https://sonarsource.atlassian.net/browse/SLCORE-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-991 Synchronize the multi-quality mode setting

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/RuleSetChangedEvent.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/RuleSetChangedEventParser.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/common/ImpactPayload.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/rules/RulesApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/rules/ServerActiveRule.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/push/PushApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AnalyzerConfigurationStorage.java, backend/server-connection/src/main/proto/sonarlint.proto, medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java
[SLCORE-998](https://sonarsource.atlassian.net/browse/SLCORE-998)
[SLCORE-998]: https://sonarsource.atlassian.net/browse/SLCORE-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-998 React to impact changes in the RuleSetChanged event

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/hotspot/HotspotService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/rules/RulesServiceTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerConnection.java, medium-tests/src/test/java/mediumtest/ConnectedHotspotMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/RulesInConnectedModeMediumTests.java, medium-tests/src/test/java/mediumtest/hotspots/HotspotLocalDetectionSupportMediumTests.java, medium-tests/src/test/java/mediumtest/rules/RuleDetailsMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/hotspot/HotspotRpcService.java
[SLCORE-1017](https://sonarsource.atlassian.net/browse/SLCORE-1017)
[SLCORE-1017]: https://sonarsource.atlassian.net/browse/SLCORE-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1017 Drop remaining code related to SQ < 9.9

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/DtoMapper.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/hotspot/HotspotService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/mode/SeverityModeService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/mode/package-info.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/reporting/FindingReportingService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetailsAdapter.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerConnection.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerInfoSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/StoredServerInfo.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ServerInfoStorage.java, backend/server-connection/src/main/proto/sonarlint.proto, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/ServerInfoSynchronizerTests.java, medium-tests/src/test/java/mediumtest/issues/IssueEventsMediumTests.java, medium-tests/src/test/java/mediumtest/synchronization/ServerInfoSynchronizationMediumTests.java, medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintLauncherBuilder.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/adapter/EitherStandardOrMQRModeAdapterFactory.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/hotspot/RaisedHotspotDto.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/issue/RaisedFindingDto.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/issue/RaisedIssueDto.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/common/MQRModeDetails.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/common/StandardModeDetails.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/common/package-info.java
[SLCORE-992](https://sonarsource.atlassian.net/browse/SLCORE-992)
[SLCORE-992]: https://sonarsource.atlassian.net/browse/SLCORE-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-992 Adapt RaisedFindingDto to include mode-specific data

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, medium-tests/src/test/java/mediumtest/analysis/RulesInConnectedModeMediumTests.java, medium-tests/src/test/java/mediumtest/rules/RuleDetailsMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/initialize/InitializeParams.java
[SLCORE-986](https://sonarsource.atlassian.net/browse/SLCORE-986)
[SLCORE-986]: https://sonarsource.atlassian.net/browse/SLCORE-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-986 Support Jupyter Notebooks in connected mode

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java
[SLCORE-927](https://sonarsource.atlassian.net/browse/SLCORE-927)
[SLCORE-927]: https://sonarsource.atlassian.net/browse/SLCORE-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-927 Fix git utils

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetails.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetailsAdapter.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/rules/RulesServiceTests.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/RuleSetChangedEvent.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/RuleSetChangedEventParser.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/common/ImpactPayload.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/rules/RulesApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/rules/ServerActiveRule.java, backend/server-api/src/main/proto/sonarqube/ws-rules.proto, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/push/PushApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AnalyzerConfigurationStorage.java, backend/server-connection/src/main/proto/sonarlint.proto, medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java
[SLCORE-998](https://sonarsource.atlassian.net/browse/SLCORE-998)
[SLCORE-998]: https://sonarsource.atlassian.net/browse/SLCORE-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-959 Custom Severities

.cirrus.star, .cirrus.yml
[SLCORE-1020](https://sonarsource.atlassian.net/browse/SLCORE-1020)
[SLCORE-1020]: https://sonarsource.atlassian.net/browse/SLCORE-1020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1020 Migrate to cirrus-modules v3

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/ImpactSeverity.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetails.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/rules/RulesApi.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/TaintIssueDownloader.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/TaintIssueDownloaderTests.java
[SLCORE-1023](https://sonarsource.atlassian.net/browse/SLCORE-1023)
[SLCORE-1023]: https://sonarsource.atlassian.net/browse/SLCORE-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1023 Parsing impact severity with INFO and BLOCKER should work

backend/core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/exception/ProjectNotFoundException.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/exception/ProjectNotFoundExceptionTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerVersionAndStatusChecker.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/ServerVersionAndStatusCheckerTests.java, medium-tests/src/test/java/mediumtest/connection/ConnectionValidatorMediumTests.java, medium-tests/src/test/java/mediumtest/issues/CheckResolutionStatusChangePermittedMediumTests.java
[SLCORE-1035](https://sonarsource.atlassian.net/browse/SLCORE-1035)
[SLCORE-1035]: https://sonarsource.atlassian.net/browse/SLCORE-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1035 Handle rebranding labels for notifications

.cirrus.yml
[SLCORE-1042](https://sonarsource.atlassian.net/browse/SLCORE-1042)
[SLCORE-1042]: https://sonarsource.atlassian.net/browse/SLCORE-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1042 Fix Orchestrator build version on 10.8

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1046](https://sonarsource.atlassian.net/browse/SLCORE-1046)
[SLCORE-1046]: https://sonarsource.atlassian.net/browse/SLCORE-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1046 Prepare for next development iteration

backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/PluginsLoader.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java
=> SLCORE-1049 Add textdeveloper to the connected mode allow-list

medium-tests/src/test/java/mediumtest/ConnectedHotspotMediumTests.java, medium-tests/src/test/java/mediumtest/taint/vulnerabilities/TaintVulnerabilityEventsMediumTests.java
[SLCORE-1053](https://sonarsource.atlassian.net/browse/SLCORE-1053)
[SLCORE-1053]: https://sonarsource.atlassian.net/browse/SLCORE-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1053 Wait long enough to receive hotspots

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SonarProjectBranchesSynchronizationService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandlerTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandlerTests.java, medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/issue/IssueDetailsDto.java
[SLCORE-1051](https://sonarsource.atlassian.net/browse/SLCORE-1051)
[SLCORE-1051]: https://sonarsource.atlassian.net/browse/SLCORE-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1051 Allow null value for branch during Open in IDE requests

pom.xml
[SLCORE-1056](https://sonarsource.atlassian.net/browse/SLCORE-1056)
Also update license information.
[SLCORE-1056]: https://sonarsource.atlassian.net/browse/SLCORE-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1056: Update Parent POM

.cirrus.yml, its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
[SLCORE-1058](https://sonarsource.atlassian.net/browse/SLCORE-1058)
[SLCORE-1058]: https://sonarsource.atlassian.net/browse/SLCORE-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1058 Fix authentication issue in QA

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1062](https://sonarsource.atlassian.net/browse/SLCORE-1062)
[SLCORE-1062]: https://sonarsource.atlassian.net/browse/SLCORE-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1062 Prepare next dev iteration

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1071](https://sonarsource.atlassian.net/browse/SLCORE-1071)
[SLCORE-1071]: https://sonarsource.atlassian.net/browse/SLCORE-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1071 Prepare next development iteration for 10.11.2

backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowHotspotRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandlerTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandlerTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysysForcedByClientMediumTests.java, medium-tests/src/test/java/mediumtest/hotspots/OpenHotspotInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenFixSuggestionInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java
[SLCORE-1067](https://sonarsource.atlassian.net/browse/SLCORE-1067)
[SLCORE-1066](https://sonarsource.atlassian.net/browse/SLCORE-1066)
[SLCORE-1067]: https://sonarsource.atlassian.net/browse/SLCORE-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLCORE-1066]: https://sonarsource.atlassian.net/browse/SLCORE-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1067 SLCORE-1066 SOQ-10

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1068](https://sonarsource.atlassian.net/browse/SLCORE-1068)
[SLCORE-1068]: https://sonarsource.atlassian.net/browse/SLCORE-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1068 Prepare next dev iteration

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/NodeJsService.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java, medium-tests/src/test/java/mediumtest/fixtures/SonarLintBackendFixture.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/initialize/JsTsRequirementsDto.java
[SLCORE-1059](https://sonarsource.atlassian.net/browse/SLCORE-1059)
[SLCORE-1059]: https://sonarsource.atlassian.net/browse/SLCORE-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1059 add 'bundlePath' to the initialization params

backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetailsAdapter.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/rules/RulesApiTests.java, medium-tests/src/test/java/mediumtest/EffectiveRulesMediumTests.java, medium-tests/src/test/java/mediumtest/http/AuthenticationMediumTests.java, medium-tests/src/test/java/mediumtest/http/ProxyMediumTests.java
[SLCORE-1091](https://sonarsource.atlassian.net/browse/SLCORE-1091)
[SLCORE-1091]: https://sonarsource.atlassian.net/browse/SLCORE-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1091 handle rules with one section only

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1096](https://sonarsource.atlassian.net/browse/SLCORE-1096)
[SLCORE-1096]: https://sonarsource.atlassian.net/browse/SLCORE-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1096 Prepare for next development iteration

backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/CspFilter.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/EmbeddedServer.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/CspFilterTest.java, medium-tests/src/test/java/mediumtest/EmbeddedServerMediumTests.java
=> SLCORE-1063 add csp header to slcore endpoint responses

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerVersionAndStatusChecker.java, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, medium-tests/src/test/java/mediumtest/http/AuthenticationMediumTests.java, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
Tested connection creation with:
=> SLCORE-1098 fix condition to use bearer auth starting SQS 10.4

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml
[SLCORE-1100](https://sonarsource.atlassian.net/browse/SLCORE-1100)
[SLCORE-1100]: https://sonarsource.atlassian.net/browse/SLCORE-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1100 Prepare for next development iteration

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/api/SonarLanguage.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/PluginsLoader.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizerTests.java, client/java-client-utils/src/main/java/org/sonarsource/sonarlint/core/client/utils/Language.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/common/Language.java
Tested with
[SLCORE-977](https://sonarsource.atlassian.net/browse/SLCORE-977)
[SLCORE-1095](https://sonarsource.atlassian.net/browse/SLCORE-1095)
[SLCORE-977]: https://sonarsource.atlassian.net/browse/SLCORE-977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLCORE-1095]: https://sonarsource.atlassian.net/browse/SLCORE-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-977, SLCORE-1095 Ansible support

pom.xml
[SLCORE-1102](https://sonarsource.atlassian.net/browse/SLCORE-1102)
[SLCORE-1102]: https://sonarsource.atlassian.net/browse/SLCORE-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1102 Use v11 of sonar-plugin-api

medium-tests/src/test/java/mediumtest/dogfooding/DogfoodingRpcServiceMediumTests.java
[SLCORE-1104](https://sonarsource.atlassian.net/browse/SLCORE-1104)
[SLCORE-1104]: https://sonarsource.atlassian.net/browse/SLCORE-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1104 Ignore dogfooding env variable on dev machine in test

pom.xml
[SLCORE-1108](https://sonarsource.atlassian.net/browse/SLCORE-1108)
Prepare for SQ LTA.
[SLCORE-1108]: https://sonarsource.atlassian.net/browse/SLCORE-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1108: Update Sonar Plugin API

test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/junit5/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/plugins/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/plugins/src/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/sse/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/websockets/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/package-info.java
[SLCORE-1115](https://sonarsource.atlassian.net/browse/SLCORE-1115)
[SLCORE-1115]: https://sonarsource.atlassian.net/browse/SLCORE-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1115 Fix Quality Gate

backend/core/src/main/java/org/sonarsource/sonarlint/core/branch/SonarProjectBranchTrackingService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/file/PathTranslationService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/file/ServerFilePathsProvider.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/nodejs/NodeJsHelper.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/branch/SonarProjectBranchTrackingServiceTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/file/PathTranslationServiceTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/file/ServerFilePathsProviderTest.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/nodejs/NodeJsHelperTests.java, medium-tests/src/test/java/mediumtest/synchronization/BranchSpecificSynchronizationMediumTests.java
[SLCORE-1109](https://sonarsource.atlassian.net/browse/SLCORE-1109)
[SLCORE-1109]: https://sonarsource.atlassian.net/browse/SLCORE-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1109 Fix irregularity of the logger instantiation

test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ServerSecurityHotspotFixture.java
[SLCORE-1127](https://sonarsource.atlassian.net/browse/SLCORE-1127)
[SLCORE-1127]: https://sonarsource.atlassian.net/browse/SLCORE-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1127 Fix code smells

backend/core/src/test/java/org/sonarsource/sonarlint/core/file/PathTranslationServiceTests.java
[SLCORE-1128](https://sonarsource.atlassian.net/browse/SLCORE-1128)
[SLCORE-1128]: https://sonarsource.atlassian.net/browse/SLCORE-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1128 Fix code smell

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1132](https://sonarsource.atlassian.net/browse/SLCORE-1132)
[SLCORE-1132]: https://sonarsource.atlassian.net/browse/SLCORE-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1132 Prepare for next development iteration

.github/workflows/release.yml, .github/workflows/slack_notify.yml, backend/core/src/main/java/org/sonarsource/sonarlint/core/connection/package-info.java
[SLCORE-1138](https://sonarsource.atlassian.net/browse/SLCORE-1138)
[SLCORE-1138]: https://sonarsource.atlassian.net/browse/SLCORE-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1138 Fix build on master

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/EmbeddedServer.java, backend/http/pom.xml, backend/http/src/main/java/org/sonarsource/sonarlint/core/http/RedirectInterceptor.java, backend/telemetry/pom.xml, medium-tests/pom.xml, pom.xml, test-utils/pom.xml
[SLCORE-1131](https://sonarsource.atlassian.net/browse/SLCORE-1131)
[SLCORE-1131]: https://sonarsource.atlassian.net/browse/SLCORE-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1131 Bump dependency versions

backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/StringUtilsTests.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowHotspotRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/StatusRequestHandler.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/smartnotifications/SmartNotifications.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/events/SmartNotificationEvent.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandlerTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/websocket/parsing/SmartNotificationEventParserTests.java
[SLCORE-1083](https://sonarsource.atlassian.net/browse/SLCORE-1083)
[SLCORE-1083]: https://sonarsource.atlassian.net/browse/SLCORE-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1083 Fix SSF-700

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/SonarLintUserHome.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/SonarLintUserHomeTests.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/UserPaths.java, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java
[SLCORE-1147](https://sonarsource.atlassian.net/browse/SLCORE-1147)
[SLCORE-1147]: https://sonarsource.atlassian.net/browse/SLCORE-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1147 Add a default implementation to didReceiveServerHotspotEvent

medium-tests/pom.xml, medium-tests/src/test/java/mediumtest/ConnectedIssueMediumTests.java, medium-tests/src/test/java/mediumtest/EffectiveRulesMediumTests.java, medium-tests/src/test/java/mediumtest/StandaloneIssueMediumTests.java, medium-tests/src/test/java/mediumtest/StandaloneRulesMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java, medium-tests/src/test/java/mediumtest/http/AuthenticationMediumTests.java, medium-tests/src/test/java/mediumtest/http/ProxyMediumTests.java, medium-tests/src/test/java/mediumtest/issues/IssueEventsMediumTests.java, medium-tests/src/test/java/mediumtest/synchronization/PluginSynchronizationMediumTests.java, medium-tests/src/test/java/utils/AnalysisUtils.java, medium-tests/src/test/java/utils/PluginLocator.java, medium-tests/src/test/java/utils/TestPlugin.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/plugins/Plugin.java
[SLCORE-1143](https://sonarsource.atlassian.net/browse/SLCORE-1143)
[SLCORE-1143]: https://sonarsource.atlassian.net/browse/SLCORE-1143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1143 NO-JIRA Add tests to verify Java SE rules execution

.cirrus.yml, its/README.md, its/tests/src/test/java/its/SonarCloudTests.java
[SLCORE-1116](https://sonarsource.atlassian.net/browse/SLCORE-1116)
The option to log in with username/password will be removed from SonarQube Cloud in the future.
[SLCORE-1116]: https://sonarsource.atlassian.net/browse/SLCORE-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1116: Token for SonarQube Cloud ITs

medium-tests/src/test/java/mediumtest/ConnectionSetupMediumTests.java, medium-tests/src/test/java/mediumtest/connection/ConnectionGetAllProjectsMediumTests.java, medium-tests/src/test/java/mediumtest/connection/ConnectionValidatorMediumTests.java, medium-tests/src/test/java/mediumtest/connection/OrganizationMediumTests.java, medium-tests/src/test/java/mediumtest/http/SslMediumTests.java, medium-tests/src/test/java/mediumtest/http/TimeoutMediumTests.java
[SLCORE-1165](https://sonarsource.atlassian.net/browse/SLCORE-1165)
[SLCORE-1165]: https://sonarsource.atlassian.net/browse/SLCORE-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1165 Fix quality gate

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisFinishedEvent.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisStartedEvent.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java
[SLCORE-983](https://sonarsource.atlassian.net/browse/SLCORE-983)
[SLCORE-983]: https://sonarsource.atlassian.net/browse/SLCORE-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-983 Remove enableTracking flag

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/FailSafeExecutors.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingSuggestionProvider.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionSuggestionProvider.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/VersionSoonUnsupportedHelper.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/commons/SmartCancelableLoadingCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/server/event/ServerEventsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/smartnotifications/SmartNotifications.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/FindingsSynchronizationService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/streaming/Alarm.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/SonarCloudWebSocket.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/WebSocketService.java, backend/http/src/main/java/org/sonarsource/sonarlint/core/http/HttpClientProvider.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/stream/EventStream.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SingleThreadedMessageConsumer.java
[SLCORE-1156](https://sonarsource.atlassian.net/browse/SLCORE-1156)
[SLCORE-1156]: https://sonarsource.atlassian.net/browse/SLCORE-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1156 Make sure exceptions are logged from executor services

backend/core/src/main/java/org/sonarsource/sonarlint/core/file/ServerFilePathsProvider.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/file/ServerFilePathsProviderTest.java, medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java
[SLCORE-1175](https://sonarsource.atlassian.net/browse/SLCORE-1175)
[SLCORE-1175]: https://sonarsource.atlassian.net/browse/SLCORE-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1175 Fix wrong parameter injection

backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java
[SLCORE-1179](https://sonarsource.atlassian.net/browse/SLCORE-1179)
SLCORE-1179
[SLCORE-1179]: https://sonarsource.atlassian.net/browse/SLCORE-1179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1179 Synchronize and use C# Enterprise with SQ:Server 10.8+ when appropriate

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisEngineCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsRepository.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/KnownFindingsStorageService.java
[SLCORE-1180](https://sonarsource.atlassian.net/browse/SLCORE-1180)
[SLCORE-1180]: https://sonarsource.atlassian.net/browse/SLCORE-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1180 Avoid multiple known findings store to be created

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/slf4j-sonar-log/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1182](https://sonarsource.atlassian.net/browse/SLCORE-1182)
[SLCORE-1182]: https://sonarsource.atlassian.net/browse/SLCORE-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1182 Prepare for next dev iteration

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/OrganizationsCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/remediation/aicodefix/AiCodeFixService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/FixSuggestionsApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/OrganizationConfigsResponseDto.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/SuggestionFeatureEnablement.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/organization/GetOrganizationsResponseDto.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/organization/OrganizationApi.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/FixSuggestionsApiTest.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/organization/OrganizationApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AiCodeFixFeatureEnablement.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AiCodeFixSettingsSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ConnectionStorage.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/Organization.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/OrganizationSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/OrganizationStorage.java, backend/server-connection/src/main/proto/sonarlint.proto, its/tests/src/test/java/its/SonarCloudTests.java, medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/AiCodeFixFixtures.java
[SLCORE-1159](https://sonarsource.atlassian.net/browse/SLCORE-1159)
[SLCORE-1159]: https://sonarsource.atlassian.net/browse/SLCORE-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1159 Expose if issue is fixable when feature is enabled

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/BlameParser.java
[SLCORE-1186](https://sonarsource.atlassian.net/browse/SLCORE-1186)
[SLCORE-1186]: https://sonarsource.atlassian.net/browse/SLCORE-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1186 Fix array out bounds error for native git blame

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/ProcessWrapperFactory.java
[SLCORE-1188](https://sonarsource.atlassian.net/browse/SLCORE-1188)
[SLCORE-1188]: https://sonarsource.atlassian.net/browse/SLCORE-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1188 Improve git blame logging for failed command execution

backend/core/src/main/java/org/sonarsource/sonarlint/core/reporting/FindingReportingService.java
[SLCORE-1191](https://sonarsource.atlassian.net/browse/SLCORE-1191)
[SLCORE-1191]: https://sonarsource.atlassian.net/browse/SLCORE-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1191 Avoid ConcurrentModificationException during issue streaming

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtilsTest.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java
[SLCORE-1195](https://sonarsource.atlassian.net/browse/SLCORE-1195)
[SLCORE-1195]: https://sonarsource.atlassian.net/browse/SLCORE-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1195 Use absolute paths to git blame files

medium-tests/src/test/java/mediumtest/hotspots/HotspotEventsMediumTests.java, medium-tests/src/test/java/mediumtest/issues/IssueEventsMediumTests.java, medium-tests/src/test/java/mediumtest/rules/RuleEventsMediumTests.java, medium-tests/src/test/java/mediumtest/server/events/ServerSentEventsMediumTests.java, medium-tests/src/test/java/mediumtest/taint/vulnerabilities/TaintVulnerabilityEventsMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/sse/SSEServer.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/sse/SSEServlet.java
[SLCORE-1200](https://sonarsource.atlassian.net/browse/SLCORE-1200)
[SLCORE-1200]: https://sonarsource.atlassian.net/browse/SLCORE-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1200 Speed up execution of server-sent events medium tests

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1203](https://sonarsource.atlassian.net/browse/SLCORE-1203)
[SLCORE-1203]: https://sonarsource.atlassian.net/browse/SLCORE-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1203 Prepare for next dev iteration

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/smartnotifications/SmartNotifications.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/ConnectionRpcServiceDelegate.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/developers/DevelopersApi.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/developers/DevelopersApiTests.java, medium-tests/src/test/java/mediumtest/ConnectionSetupMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/connection/ConnectionRpcService.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[SLCORE-1199](https://sonarsource.atlassian.net/browse/SLCORE-1199)
[SLCORE-1199]: https://sonarsource.atlassian.net/browse/SLCORE-1199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1199 Stop checking if smart notifications are supported

backend/core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueService.java, medium-tests/src/test/java/mediumtest/issues/IssuesStatusChangeMediumTests.java, medium-tests/src/test/java/mediumtest/synchronization/ConnectionSyncMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[SLCORE-1206](https://sonarsource.atlassian.net/browse/SLCORE-1206)
[SLCORE-1206]: https://sonarsource.atlassian.net/browse/SLCORE-1206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1206 Fix add issue comment for VS client

backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java
[SLCORE-1201](https://sonarsource.atlassian.net/browse/SLCORE-1201)
[SLCORE-1201]: https://sonarsource.atlassian.net/browse/SLCORE-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1201 Fix SSF-736

medium-tests/src/test/java/mediumtest/hotspots/HotspotEventsMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ServerSecurityHotspotFixture.java
[SLCORE-1204](https://sonarsource.atlassian.net/browse/SLCORE-1204)
[SLCORE-1204]: https://sonarsource.atlassian.net/browse/SLCORE-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1204 add medium test for HotspotChangedEvent

.github/workflows/PullRequestClosed.yml
[SLCORE-1214](https://sonarsource.atlassian.net/browse/SLCORE-1214)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLCORE-1214]: https://sonarsource.atlassian.net/browse/SLCORE-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1214 Autoclose issues created by Jira integration

medium-tests/src/test/java/mediumtest/issues/IssuesStatusChangeMediumTests.java
[SLCORE-1154](https://sonarsource.atlassian.net/browse/SLCORE-1154)
Make Master Green Again.
[SLCORE-1154]: https://sonarsource.atlassian.net/browse/SLCORE-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1154: Fix test from upstream master

medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java
[SLCORE-1184](https://sonarsource.atlassian.net/browse/SLCORE-1184)
Make Master Green Again.
[SLCORE-1184]: https://sonarsource.atlassian.net/browse/SLCORE-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1184: Fix red master

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtils.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/ProcessWrapperFactory.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/exceptions/GitException.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/exceptions/GitRepoNotFoundException.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/exceptions/NoSuchPathException.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/exceptions/package-info.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/GitUtilsTest.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java
[SLCORE-1212](https://sonarsource.atlassian.net/browse/SLCORE-1212)
[SLCORE-1212]: https://sonarsource.atlassian.net/browse/SLCORE-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1212 Don't fail on git blaming newly created file

backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTests.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryMeasuresPayloadTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java
[SLCORE-1222](https://sonarsource.atlassian.net/browse/SLCORE-1222)
[SLCORE-1222]: https://sonarsource.atlassian.net/browse/SLCORE-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1222 Do not send project keys as part of the telemetry

its/tests/src/test/java/its/SonarCloudTests.java
[SLCORE-1227](https://sonarsource.atlassian.net/browse/SLCORE-1227)
[SLCORE-1227]: https://sonarsource.atlassian.net/browse/SLCORE-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1227 Update a test consecutive to a severity change in an analyzer

backend/core/src/main/java/org/sonarsource/sonarlint/core/smartnotifications/SmartNotifications.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/WebSocketManager.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/WebSocketService.java, medium-tests/src/test/java/mediumtest/websockets/WebSocketMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/websockets/WebSocketEndpoint.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/websockets/WebSocketServer.java
[SLCORE-1171](https://sonarsource.atlassian.net/browse/SLCORE-1171)
[SLCORE-1171]: https://sonarsource.atlassian.net/browse/SLCORE-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1171 properly manage WebSocket connections with multi-region

medium-tests/src/test/java/mediumtest/rules/OkRulesDefinition.java, medium-tests/src/test/java/mediumtest/rules/RuleExtractionMediumTests.java, medium-tests/src/test/java/mediumtest/rules/ThrowingRulesDefinition.java
[SLCORE-1225](https://sonarsource.atlassian.net/browse/SLCORE-1225)
[SLCORE-1225]: https://sonarsource.atlassian.net/browse/SLCORE-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1225 Fail gracefully when plugin fails to define its rules

backend/core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/remediation/aicodefix/AiCodeFixFeature.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/remediation/aicodefix/AiCodeFixService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/reporting/FindingReportingService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TaintVulnerabilityTrackingService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/FixSuggestionsApi.java, medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ServerTaintIssueFixtures.java
[SLCORE-1228](https://sonarsource.atlassian.net/browse/SLCORE-1228)
[SLCORE-1228]: https://sonarsource.atlassian.net/browse/SLCORE-1228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1228 Let client suggest AI CodeFix for taint vulnerabilities

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1231](https://sonarsource.atlassian.net/browse/SLCORE-1231)
=> SLCORE-1231 Prepare next dev iteration

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/SonarLintBlameResult.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/BlameParser.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitService.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/NativeGitWrapper.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/ProcessWrapperFactory.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/WinGitUtils.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/exceptions/GitException.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/SonarLintBlameResultTest.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/BlameParserTests.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/GitServiceTests.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/NativeGitWrapperTests.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/ProcessWrapperFactoryTests.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java
[SLCORE-1226](https://sonarsource.atlassian.net/browse/SLCORE-1226)
[SLCORE-1226]: https://sonarsource.atlassian.net/browse/SLCORE-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1226 Native git blame rework

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionManager.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/SonarProjectsCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/event/ConnectionConfigurationUpdatedEvent.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/server/event/ServerEventsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/websocket/WebSocketService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/ConnectionServiceTests.java, medium-tests/src/test/java/mediumtest/synchronization/ConnectionSyncMediumTests.java
[SLCORE-1234](https://sonarsource.atlassian.net/browse/SLCORE-1234)
[SLCORE-1234]: https://sonarsource.atlassian.net/browse/SLCORE-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1234 Evict connections cache when needed

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisQueue.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/api/TriggerType.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/command/AnalyzeCommand.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/AnalysisQueueTest.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/mediumtests/AnalysisSchedulerMediumTests.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/fs/FileExclusionService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java
[SLCORE-1081](https://sonarsource.atlassian.net/browse/SLCORE-1081)
[SLCORE-1081]: https://sonarsource.atlassian.net/browse/SLCORE-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1081 Batch automatic analyses

backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/SecurityHotspotRaisedEventParser.java, medium-tests/src/test/java/mediumtest/hotspots/HotspotEventsMediumTests.java, medium-tests/src/test/java/mediumtest/websockets/WebSocketMediumTests.java
I should have done this change from the very beginning.
In any case, once https://github.com/SonarSource/sonar-enterprise/pull/13291 is released, we will have access to hotspot resolution.
=> SLCORE-1240 take hotspot resolution into account

API_CHANGES.md, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/api/AnalysisResults.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/command/AnalyzeCommand.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisFinishedEvent.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/analysis/AnalyzeFilesAndTrackParams.java
[SLCORE-1239](https://sonarsource.atlassian.net/browse/SLCORE-1239)
[SLCORE-1239]: https://sonarsource.atlassian.net/browse/SLCORE-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1239 Deprecate AnalyzeFilesAndTrackParams.startTime

backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetails.java, its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
[SLCORE-1255](https://sonarsource.atlassian.net/browse/SLCORE-1255)
[SLCORE-1255]: https://sonarsource.atlassian.net/browse/SLCORE-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1255 Use correct rule type for a custom rule derived from a template

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisQueue.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/AnalysisQueueTest.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisSchedulerCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AbstractRpcServiceDelegate.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisRpcServiceDelegate.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisCancellationMediumTests.java
[SLCORE-1238](https://sonarsource.atlassian.net/browse/SLCORE-1238)
[SLCORE-1238]: https://sonarsource.atlassian.net/browse/SLCORE-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1238 Cancel scheduled analyses that are not ready for a while

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1259](https://sonarsource.atlassian.net/browse/SLCORE-1259)
[SLCORE-1259]: https://sonarsource.atlassian.net/browse/SLCORE-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1259 Prepare for next development iteration

.github/workflows/slack_notify.yml
[BUILD-7788](https://sonarsource.atlassian.net/browse/BUILD-7788)
[BUILD-7788]: https://sonarsource.atlassian.net/browse/BUILD-7788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-7788 action runs on ubuntu-latest for public repos

client/java-client-utils/src/main/java/org/sonarsource/sonarlint/core/client/utils/ClientFileExclusions.java, client/java-client-utils/src/test/java/org/sonarsource/sonarlint/core/client/utils/ClientFileExclusionsTests.java
[SLI-1956](https://sonarsource.atlassian.net/browse/SLI-1956)
[SLI-1956]: https://sonarsource.atlassian.net/browse/SLI-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1256 Make File Exclusions IDE/OS Agnostic

its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
[SLCORE-1274](https://sonarsource.atlassian.net/browse/SLCORE-1274)
[SLCORE-1274]: https://sonarsource.atlassian.net/browse/SLCORE-1274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1274 Fix SonarQubeDeveloperEditonTests

its/tests/projects/sample-cloudformation/src/sample.yaml, its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java
[SLCORE-1277](https://sonarsource.atlassian.net/browse/SLCORE-1277)
[SLCORE-1277]: https://sonarsource.atlassian.net/browse/SLCORE-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1277 Update The CloudFormation Test Input File

backend/core/src/main/java/org/sonarsource/sonarlint/core/http/ConnectionAwareHttpClientProvider.java, medium-tests/src/test/java/mediumtest/http/AuthenticationMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java
[SLCORE-1275](https://sonarsource.atlassian.net/browse/SLCORE-1275)
[SLCORE-1275]: https://sonarsource.atlassian.net/browse/SLCORE-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1275 Throw if the client does not return credentials for a given connection

backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/organization/OrganizationApi.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AiCodeFixSettingsSynchronizer.java, medium-tests/src/test/java/mediumtest/SharedConnectedModeSettingsMediumTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java, medium-tests/src/test/java/mediumtest/connection/ConnectionGetAllProjectsMediumTests.java, medium-tests/src/test/java/mediumtest/connection/ConnectionGetProjectNameByKeyMediumTests.java, medium-tests/src/test/java/mediumtest/hotspots/HotspotCheckStatusChangePermittedMediumTests.java, medium-tests/src/test/java/mediumtest/hotspots/OpenHotspotInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/CheckResolutionStatusChangePermittedMediumTests.java, medium-tests/src/test/java/mediumtest/issues/IssuesStatusChangeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenFixSuggestionInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java, medium-tests/src/test/java/mediumtest/rules/RuleDetailsMediumTests.java, medium-tests/src/test/java/mediumtest/synchronization/ServerInfoSynchronizationMediumTests.java, medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/junit5/SonarLintTestHarness.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[SLCORE-1273](https://sonarsource.atlassian.net/browse/SLCORE-1273)
[SLCORE-1273]: https://sonarsource.atlassian.net/browse/SLCORE-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1273 Do not fetch AI CodeFix organization config if user does not belong

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresValue.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java
[SLCORE-1260](https://sonarsource.atlassian.net/browse/SLCORE-1260)
[SLCORE-1260]: https://sonarsource.atlassian.net/browse/SLCORE-1260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1260 Report all applied fixes in a single per-install counter

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1289](https://sonarsource.atlassian.net/browse/SLCORE-1289)
[SLCORE-1289]: https://sonarsource.atlassian.net/browse/SLCORE-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1289 Prepare for next development iteration

its/tests/pom.xml
[SLCORE-1297](https://sonarsource.atlassian.net/browse/SLCORE-1297)
[SLCORE-1297]: https://sonarsource.atlassian.net/browse/SLCORE-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1297 Update Orchestrator version to 5.4.0

its/tests/pom.xml
[SLCORE-1297](https://sonarsource.atlassian.net/browse/SLCORE-1297)
[SLCORE-1297]: https://sonarsource.atlassian.net/browse/SLCORE-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1297 Update Orchestrator version to 5.5.0

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/command/AnalyzeCommand.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisMediumTests.java
[SLCORE-1295](https://sonarsource.atlassian.net/browse/SLCORE-1295)
[SLCORE-1295]: https://sonarsource.atlassian.net/browse/SLCORE-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1295 Mark the progress as cancellable for the analysis

backend/core/src/main/java/org/sonarsource/sonarlint/core/event/MatchingSessionEndedEvent.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/matching/MatchingSession.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClient.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java
[SLCORE-1220](https://sonarsource.atlassian.net/browse/SLCORE-1220)
[SLCORE-1221](https://sonarsource.atlassian.net/browse/SLCORE-1221)
[SLCORE-1220]: https://sonarsource.atlassian.net/browse/SLCORE-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLCORE-1221]: https://sonarsource.atlassian.net/browse/SLCORE-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1220 SLCORE-1221 Report found and fixed issues as telemetry measures

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/RawIssue.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TextRangeUtils.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/matching/IssueMatcher.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/matching/MatchingResult.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/matching/MatchingSession.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/matching/RawIssueFindingMatchingAttributeMapper.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/issue/matching/IssueMatcherTests.java, backend/rpc-impl/src/test/java/org/sonarsource/sonarlint/core/rpc/impl/AnalysisServiceTests.java, medium-tests/src/test/java/mediumtest/StandaloneIssueMediumTests.java
[SLCORE-1285](https://sonarsource.atlassian.net/browse/SLCORE-1285)
[SLCORE-1285]: https://sonarsource.atlassian.net/browse/SLCORE-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1285 Improve issue streaming performance with high number of issues

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingCandidatesFinder.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingSuggestionProvider.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/SonarProjectsCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/remediation/aicodefix/AiCodeFixService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/BindingSuggestionProviderTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/SonarProjectsCacheTests.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/component/Component.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/component/ComponentApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/component/ServerProject.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/features/FeaturesApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/features/package-info.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/AiSuggestionRequestBodyDto.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/FixSuggestionsApi.java, backend/server-api/src/main/proto/sonarqube/ws-components.proto, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/component/ComponentApiTests.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/component/ServerProjectTests.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/FixSuggestionsApiTest.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AiCodeFixSettingsSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[MMF-4471](https://sonarsource.atlassian.net/browse/MMF-4471)
[MMF-4471]: https://sonarsource.atlassian.net/browse/MMF-4471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MMF-4471 Enable AI CodeFix in the IDE for SQS users

pom.xml
[SLCORE-1308](https://sonarsource.atlassian.net/browse/SLCORE-1308)
[SLCORE-1308]: https://sonarsource.atlassian.net/browse/SLCORE-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1308 Update httpclient5 version to 5.4.4

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1309](https://sonarsource.atlassian.net/browse/SLCORE-1309)
[SLCORE-1309]: https://sonarsource.atlassian.net/browse/SLCORE-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1309 Prepare for next development iteration

backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/features/Feature.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/features/FeaturesApi.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/AiCodeFixSettingsSynchronizer.java
[SLCORE-1339](https://sonarsource.atlassian.net/browse/SLCORE-1339)
[SLCORE-1339]: https://sonarsource.atlassian.net/browse/SLCORE-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1339 Use an enum to represent a SQS feature instead of a String

backend/commons/pom.xml, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/WinGitUtils.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/WinGitUtilsTests.java
[SLCORE-1325](https://sonarsource.atlassian.net/browse/SLCORE-1325)
[SLCORE-1325]: https://sonarsource.atlassian.net/browse/SLCORE-1325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1325 Windows where.exe tool output is being parsed incorrectly for two git installations case

test-utils/pom.xml
[SLCORE-1358](https://sonarsource.atlassian.net/browse/SLCORE-1358)
[SLCORE-1358]: https://sonarsource.atlassian.net/browse/SLCORE-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1358 Upgrade tomcat to 11.0.6

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConfigurationService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionService.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/config/binding/BindingConfigurationDto.java
[SLCORE-1357](https://sonarsource.atlassian.net/browse/SLCORE-1357)
[SLCORE-1357]: https://sonarsource.atlassian.net/browse/SLCORE-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1357 Add more traces around configuration scopes

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1359](https://sonarsource.atlassian.net/browse/SLCORE-1359)
[SLCORE-1359]: https://sonarsource.atlassian.net/browse/SLCORE-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1359 Prepare for next development iteration

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisScheduler.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/mediumtests/AnalysisSchedulerMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisSchedulingMediumTests.java
[SLCORE-1341](https://sonarsource.atlassian.net/browse/SLCORE-1341)
[SLCORE-1341]: https://sonarsource.atlassian.net/browse/SLCORE-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1341 Fix NPE when an analysis command is canceled

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/TelemetryRpcServiceDelegate.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/ToolCallCounter.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/telemetry/TelemetryRpcService.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/ToolCalledParams.java
[SLCORE-1366](https://sonarsource.atlassian.net/browse/SLCORE-1366)
=> SLCORE-1373 Track tools usage

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/PluginsLoader.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizerTests.java, its/tests/pom.xml, its/tests/projects/sample-go/src/sample.go, its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java, its/tests/src/test/java/its/utils/PluginLocator.java, its/tests/src/test/resources/go-sonarlint.xml
[SLCORE-1337](https://sonarsource.atlassian.net/browse/SLCORE-1337)
SLCORE-1337
[SLCORE-1337]: https://sonarsource.atlassian.net/browse/SLCORE-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1337 Use synchronized Go analyzer where Enterprise rules should be supported

backend/core/src/main/java/org/sonarsource/sonarlint/core/smartnotifications/SmartNotifications.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/SmartNotificationsStorage.java, medium-tests/src/test/java/mediumtest/smartnotifications/SmartNotificationsMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ProjectStorageFixture.java
[SLCORE-1313](https://sonarsource.atlassian.net/browse/SLCORE-1313)
[SLCORE-1313]: https://sonarsource.atlassian.net/browse/SLCORE-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1313 Ignore storage exceptions when polling for smart notifications

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionService.java, medium-tests/src/test/java/mediumtest/connection/ConnectionValidatorMediumTests.java
[SLCORE-1380](https://sonarsource.atlassian.net/browse/SLCORE-1380)
[SLCORE-1380]: https://sonarsource.atlassian.net/browse/SLCORE-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1380 Report error during connection validation as a non-success response

pom.xml
[SLCORE-1382](https://sonarsource.atlassian.net/browse/SLCORE-1382)
[SLCORE-1382]: https://sonarsource.atlassian.net/browse/SLCORE-1382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1382 Upgrade spring version from 6.2.2 to 6.2.7

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1383](https://sonarsource.atlassian.net/browse/SLCORE-1383)
[SLCORE-1383]: https://sonarsource.atlassian.net/browse/SLCORE-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1383 Prepare for next development iteration

pom.xml
[SLCORE-1386](https://sonarsource.atlassian.net/browse/SLCORE-1386)
[SLCORE-1386]: https://sonarsource.atlassian.net/browse/SLCORE-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1386 Update JGit version to 7.2.1

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/SonarLintBlameResult.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitService.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/GitServiceTests.java
[SLCORE-1377](https://sonarsource.atlassian.net/browse/SLCORE-1377)
[SLCORE-1377]: https://sonarsource.atlassian.net/browse/SLCORE-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1377 Better handling for the git blame error

API_CHANGES.md, client/rpc-java-client/src/main/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientDelegate.java, client/rpc-java-client/src/test/java/org/sonarsource/sonarlint/core/rpc/client/SonarLintRpcClientImplTest.java, its/tests/src/test/java/its/MockSonarLintRpcClientDelegate.java, medium-tests/src/test/java/mediumtest/branch/SonarProjectBranchMediumTests.java, medium-tests/src/test/java/mediumtest/sloop/SloopLauncherTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcClient.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/branch/MatchProjectBranchParams.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/branch/MatchProjectBranchResponse.java
[SLCORE-1372](https://sonarsource.atlassian.net/browse/SLCORE-1372)
[SLCORE-1372]: https://sonarsource.atlassian.net/browse/SLCORE-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1372 Deprecate matchProjectBranch

backend/core/src/main/java/org/sonarsource/sonarlint/core/remediation/aicodefix/AiCodeFixService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApiHelper.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/exception/TooManyRequestsException.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/fixsuggestions/FixSuggestionsApi.java, medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java
[SLCORE-1352](https://sonarsource.atlassian.net/browse/SLCORE-1352)
[SLCORE-1352]: https://sonarsource.atlassian.net/browse/SLCORE-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1352 Handle HTTP 429 from AI CodeFix service

backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/TelemetryRpcServiceDelegate.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/telemetry/TelemetryRpcService.java
[SLCORE-1397](https://sonarsource.atlassian.net/browse/SLCORE-1397)
[SLCORE-1397]: https://sonarsource.atlassian.net/browse/SLCORE-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1397 Give clients possibility to record "Hotspot investigated" as telemetry measure

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/NodeJsService.java
[SLCORE-1430](https://sonarsource.atlassian.net/browse/SLCORE-1430)
[SLCORE-1430]: https://sonarsource.atlassian.net/browse/SLCORE-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1430 Do not restart the analysis scheduler everytime Node.js path is set

backend/core/src/main/java/org/sonarsource/sonarlint/core/reporting/FindingReportingService.java, medium-tests/src/test/java/mediumtest/SonarLintTestHarnessMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisReadinessMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/junit5/SonarLintTestHarness.java
[SLCORE-1409](https://sonarsource.atlassian.net/browse/SLCORE-1409)
[SLCORE-1409]: https://sonarsource.atlassian.net/browse/SLCORE-1409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1409 Fix flaky tests

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/command/AnalyzeCommand.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/sensor/SensorsExecutor.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/module/ModuleContainer.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/Step.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/Trace.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisSchedulerCache.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/container/SpringComponentContainer.java, backend/plugin-commons/src/test/java/org/sonarsource/sonarlint/core/plugin/commons/container/SpringComponentContainerTests.java, backend/rule-extractor/src/main/java/org/sonarsource/sonarlint/core/rule/extractor/RulesDefinitionExtractor.java
[SLCORE-1242](https://sonarsource.atlassian.net/browse/SLCORE-1242)
[SLCORE-1242]: https://sonarsource.atlassian.net/browse/SLCORE-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1242 Trace "overhead" operations on analysis requests

API_CHANGES.md
[SLCORE-1416](https://sonarsource.atlassian.net/browse/SLCORE-1416)
[SLCORE-1416]: https://sonarsource.atlassian.net/browse/SLCORE-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1416 Document the changes in API_CHANGES.md

backend/core/src/main/java/org/sonarsource/sonarlint/core/TokenGeneratorHelper.java, medium-tests/src/test/java/mediumtest/ConnectionSetupMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/connection/auth/HelpGenerateUserTokenParams.java
[SLCORE-1504](https://sonarsource.atlassian.net/browse/SLCORE-1504)
[SLCORE-1504]: https://sonarsource.atlassian.net/browse/SLCORE-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1504 Replace "utm_type" parameter with "utm_medium" (as specified)

backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizer.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/PluginsSynchronizerTests.java
[SLCORE-1500](https://sonarsource.atlassian.net/browse/SLCORE-1500)
[SLCORE-1500]: https://sonarsource.atlassian.net/browse/SLCORE-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1500 Do not sync and load plugins if language is not enabled

backend/core/src/main/java/org/sonarsource/sonarlint/core/file/PathTranslationService.java
[SLCORE-1505](https://sonarsource.atlassian.net/browse/SLCORE-1505)
[SLCORE-1505]: https://sonarsource.atlassian.net/browse/SLCORE-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1505 Do not refresh path translations when config scope is removed

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/fs/FileExclusionService.java, medium-tests/src/test/java/mediumtest/file/ClientFileExclusionsMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/file/FileRpcService.java
[SLCORE-1513](https://sonarsource.atlassian.net/browse/SLCORE-1513)
[SLCORE-1513]: https://sonarsource.atlassian.net/browse/SLCORE-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1513 Getting file status should include all exclusions

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1527](https://sonarsource.atlassian.net/browse/SLCORE-1527)
=> SLCORE-1527 Prepare next development iteration

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/util/git/GitService.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/util/git/GitServiceTests.java
[SLCORE-1517](https://sonarsource.atlassian.net/browse/SLCORE-1517)
[SLCORE-1517]: https://sonarsource.atlassian.net/browse/SLCORE-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1517 Fetch git remote URL using JGit

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryAnalyzerPerformance.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryNotificationsCounter.java, medium-tests/src/test/java/mediumtest/SharedConnectedModeSettingsMediumTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisSchedulingMediumTests.java, medium-tests/src/test/java/mediumtest/analysis/sensor/WaitingCancellationSensor.java, medium-tests/src/test/java/mediumtest/hotspots/HotspotStatusChangeMediumTests.java, medium-tests/src/test/java/mediumtest/hotspots/OpenHotspotInBrowserMediumTests.java, medium-tests/src/test/java/mediumtest/hotspots/OpenHotspotInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/IssuesStatusChangeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenFixSuggestionInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/issues/OpenIssueInIdeMediumTests.java, medium-tests/src/test/java/mediumtest/newcode/NewCodeTelemetryMediumTests.java, medium-tests/src/test/java/mediumtest/remediation/aicodefix/AiCodeFixMediumTest.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintTestRpcServer.java, test-utils/src/test/java/org/sonarsource/sonarlint/core/test/utils/SonarLintTestRpcServerTest.java
[SLCORE-1494](https://sonarsource.atlassian.net/browse/SLCORE-1494)
[SLCORE-1494]: https://sonarsource.atlassian.net/browse/SLCORE-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1494 Fix flaky tests

backend/core/src/main/java/org/sonarsource/sonarlint/core/issue/IssueService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/mode/SeverityModeService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/plugin/PluginsService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/repository/rules/RulesRepository.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RulesExtractionHelper.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/HotspotSynchronizationService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/settings/SettingsApi.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/settings/SettingsApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/LocalStorageSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerInfoSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ServerSettings.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/StoredServerInfo.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ServerInfoStorage.java, backend/server-connection/src/main/proto/sonarlint.proto, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/ServerInfoSynchronizerTests.java, medium-tests/src/test/java/mediumtest/synchronization/ServerInfoSynchronizationMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[SLCORE-1522](https://sonarsource.atlassian.net/browse/SLCORE-1522)
[SLCORE-1522]: https://sonarsource.atlassian.net/browse/SLCORE-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1522 Synchronize SCA enablement setting from the server

backend/core/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryService.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/TelemetryRpcServiceDelegate.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryFindingsFilteredCounter.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorage.java, backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryHttpClientTests.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorageTests.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/TelemetryManagerTests.java, medium-tests/src/test/java/mediumtest/TelemetryMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/telemetry/TelemetryRpcService.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/FindingsFilteredParams.java
[SLCORE-1425](https://sonarsource.atlassian.net/browse/SLCORE-1425)
[SLCORE-1425]: https://sonarsource.atlassian.net/browse/SLCORE-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1425, SLCORE-1426 Telemetry for unified findings view

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryLocalStorageManager.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisReadinessMediumTests.java
[SLCORE-1494](https://sonarsource.atlassian.net/browse/SLCORE-1494)
[SLCORE-1494]: https://sonarsource.atlassian.net/browse/SLCORE-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1494 Fix flaky test

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/TelemetryFindingsFilteredCounter.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/FindingsFilteredParams.java
[SLCORE-1539](https://sonarsource.atlassian.net/browse/SLCORE-1539)
[SLCORE-1539]: https://sonarsource.atlassian.net/browse/SLCORE-1539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1539 Fix SQ issues due to missing new lines at end of file

backend/core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/ScaSynchronizationService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/SynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApiHelper.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/sca/GetIssuesReleasesResponse.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/sca/ScaApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/sca/package-info.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/sca/ScaApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/issues/ServerScaIssue.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/ProjectServerIssueStore.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/ServerIssueFixtures.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreTests.java, backend/server-connection/src/test/java/testutils/InMemoryIssueStore.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[SLCORE-1523](https://sonarsource.atlassian.net/browse/SLCORE-1523)
[SLCORE-1523]: https://sonarsource.atlassian.net/browse/SLCORE-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1523 Synchronize SCA findings from the server

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/validation/InvalidFields.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/validation/RegexpValidator.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/validation/InvalidFieldsTest.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/validation/RegexpValidatorTest.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionService.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/ConnectionServiceTests.java, medium-tests/src/test/java/mediumtest/ConnectionSetupMediumTests.java
[SLCORE-1531](https://sonarsource.atlassian.net/browse/SLCORE-1531)
[SLCORE-1531]: https://sonarsource.atlassian.net/browse/SLCORE-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1531 Add validation on UTM params on SLCore side

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingSuggestionProvider.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/BindingSuggestionProviderTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/ConnectionStorage.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/SQCProjectBindingSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/SQCSearchedProjectSynchronizer.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/StoredSQCProjectBinding.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/StoredSQCSearchedProject.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/SQCProjectBindingStorage.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/SQCSearchedProjectStorage.java, backend/server-connection/src/main/proto/sonarlint.proto
[SLCORE-1538](https://sonarsource.atlassian.net/browse/SLCORE-1538)
[SLCORE-1538]: https://sonarsource.atlassian.net/browse/SLCORE-1538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1538 Enable Caching while Fetching the Project Keys and IDs

backend/core/src/main/java/org/sonarsource/sonarlint/core/BindingSuggestionProvider.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/BindingSuggestionProviderTests.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/ProjectBindingsApi.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/SQCProjectBindingsResponse.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/SQCProjectBindingsResponseDto.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/SQSProjectBindingsResponse.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/SQSProjectBindingsResponseDto.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/ProjectBindingsApiTests.java, medium-tests/src/test/java/mediumtest/BindingSuggestionsMediumTests.java
[SLCORE-1529](https://sonarsource.atlassian.net/browse/SLCORE-1529)
[SLCORE-1529]: https://sonarsource.atlassian.net/browse/SLCORE-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1529 Implement SQS Binding

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/SonarLintPathPattern.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/filesystem/LanguageDetection.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/sensor/SonarLintSensorStorage.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/sonarapi/DefaultSonarLintIssueLocation.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/analysis/SonarLintPathPatternTests.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/analysis/sensor/SonarLintSensorStorageTests.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/sonarapi/MapSettings.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/ServerApiHelper.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/projectbindings/package-info.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/ServerApiHelperTests.java
[SLCORE-1556](https://sonarsource.atlassian.net/browse/SLCORE-1556)
[SLCORE-1556]: https://sonarsource.atlassian.net/browse/SLCORE-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1556 Remove deprecated methods following dependency fixes

backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/PluginsStorage.java, medium-tests/src/test/java/mediumtest/synchronization/PluginSynchronizationMediumTests.java
[SLCORE-1229](https://sonarsource.atlassian.net/browse/SLCORE-1229)
[SLCORE-1229]: https://sonarsource.atlassian.net/browse/SLCORE-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1229 Clean up plugin reference after cleaning up a plugin jar

backend/telemetry/src/main/java/org/sonarsource/sonarlint/core/telemetry/measures/payload/TelemetryMeasuresBuilder.java, backend/telemetry/src/test/java/org/sonarsource/sonarlint/core/telemetry/payload/TelemetryMeasuresPayloadTests.java
[SLCORE-1559](https://sonarsource.atlassian.net/browse/SLCORE-1559)
[SLCORE-1559]: https://sonarsource.atlassian.net/browse/SLCORE-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1559 Fix remote binding telemetry

backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/SonarLintCoreVersion.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/monitoring/MonitoringService.java, backend/commons/src/test/java/org/sonarsource/sonarlint/core/commons/SonarLintCoreVersionTests.java
[SLCORE-1246](https://sonarsource.atlassian.net/browse/SLCORE-1246)
[SLCORE-1246]: https://sonarsource.atlassian.net/browse/SLCORE-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1246 Use shading-resistant core version for monitoring

backend/core/src/main/java/org/sonarsource/sonarlint/core/sca/DependencyRiskService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/ScaSynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/sca/GetIssueReleaseResponse.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/sca/GetIssuesReleasesResponse.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/sca/ScaApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/issues/ServerDependencyRisk.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/ServerIssueFixtures.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreTests.java, its/tests/src/test/java/its/SonarQubeEnterpriseEditionTests.java, medium-tests/src/test/java/mediumtest/sca/DependencyRiskStatusChangeMediumTests.java, medium-tests/src/test/java/mediumtest/sca/DependencyRisksMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/sca/GetDependencyRiskDetailsResponse.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/tracking/DependencyRiskDto.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ProjectStorageFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ServerDependencyRiskFixtures.java
[SLCORE-1528](https://sonarsource.atlassian.net/browse/SLCORE-1528)
[SLCORE-1528]: https://sonarsource.atlassian.net/browse/SLCORE-1528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1528 Add quality to dependency risk response

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1582](https://sonarsource.atlassian.net/browse/SLCORE-1582)
[SLCORE-1582]: https://sonarsource.atlassian.net/browse/SLCORE-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1582 Prepare next dev iteration

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/sca/DependencyRiskService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/sync/ScaSynchronizationService.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/sca/GetIssuesReleasesResponse.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/sca/ScaApiTests.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/issues/ServerDependencyRisk.java, backend/server-connection/src/main/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStore.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/ServerIssueFixtures.java, backend/server-connection/src/test/java/org/sonarsource/sonarlint/core/serverconnection/storage/XodusServerIssueStoreTests.java, medium-tests/src/test/java/mediumtest/sca/DependencyRiskStatusChangeMediumTests.java, medium-tests/src/test/java/mediumtest/sca/DependencyRisksMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/tracking/DependencyRiskDto.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ProjectStorageFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ServerDependencyRiskFixtures.java
[SLCORE-1594](https://sonarsource.atlassian.net/browse/SLCORE-1594)
[SLCORE-1594]: https://sonarsource.atlassian.net/browse/SLCORE-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1594 Fetch CVE ID and CVE Score for SCA findings

its/tests/projects/sample-misra/foo.cpp, its/tests/src/test/java/its/SonarQubeEnterpriseEditionTests.java, its/tests/src/test/resources/cpp-misra-sonarlint.xml
[SLCORE-1506](https://sonarsource.atlassian.net/browse/SLCORE-1506)
[SLCORE-1506]: https://sonarsource.atlassian.net/browse/SLCORE-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1506 Write an integration test to verify MISRA early access rules

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/command/AnalyzeCommand.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java, medium-tests/src/test/java/mediumtest/file/ClientFileExclusionsMediumTests.java, medium-tests/src/test/java/mediumtest/tracking/IssueTrackingMediumTests.java
[SLCORE-1583](https://sonarsource.atlassian.net/browse/SLCORE-1583)
[SLCORE-1583]: https://sonarsource.atlassian.net/browse/SLCORE-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1583 Client should be notified when a non-started analysis is finished

backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/PluginsLoader.java
[SLVS-2477](https://sonarsource.atlassian.net/browse/SLVS-2477)
[SLVS-2477]: https://sonarsource.atlassian.net/browse/SLVS-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVS-2477  Add SqvsRoslyn plugin to list of allowed plugins

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionSuggestionProvider.java, medium-tests/src/test/java/mediumtest/ConnectionSuggestionMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/connection/ConnectionSuggestionDto.java
[SLCORE-1606](https://sonarsource.atlassian.net/browse/SLCORE-1606)
[SLCORE-1606]: https://sonarsource.atlassian.net/browse/SLCORE-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1606 Allow Clients To Know Connection Suggestion Origin

backend/core/src/main/java/org/sonarsource/sonarlint/core/ConnectionSuggestionProvider.java
[SLCORE-1611](https://sonarsource.atlassian.net/browse/SLCORE-1611)
[SLCORE-1611]: https://sonarsource.atlassian.net/browse/SLCORE-1611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1611 Fix Quality Gate

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1622](https://sonarsource.atlassian.net/browse/SLCORE-1622)
[SLCORE-1622]: https://sonarsource.atlassian.net/browse/SLCORE-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1622 Prepare next dev iteration

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1624](https://sonarsource.atlassian.net/browse/SLCORE-1624)
[SLCORE-1624]: https://sonarsource.atlassian.net/browse/SLCORE-1624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1624 Prepare for next development iteration

.github/workflows/shadow_scans.yml
[SLCORE-1593](https://sonarsource.atlassian.net/browse/SLCORE-1593)
[SLCORE-1593]: https://sonarsource.atlassian.net/browse/SLCORE-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1593 Fix shadow scans in cron jobs

.github/workflows/shadow_scans.yml
[BUILD-8999](https://sonarsource.atlassian.net/browse/BUILD-8999)
[BUILD-8999]: https://sonarsource.atlassian.net/browse/BUILD-8999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Fix cloning for shadow scans.
=> BUILD-8999: fix shadow scans

.github/workflows/shadow_scans.yml
[SLCORE-1593](https://sonarsource.atlassian.net/browse/SLCORE-1593)
[SLCORE-1593]: https://sonarsource.atlassian.net/browse/SLCORE-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1593 Fix coverage computation

backend/analysis-engine/pom.xml, backend/cli/pom.xml, backend/commons/pom.xml, backend/core/pom.xml, backend/http/pom.xml, backend/plugin-api/pom.xml, backend/plugin-commons/pom.xml, backend/rpc-impl/pom.xml, backend/rule-extractor/pom.xml, backend/server-api/pom.xml, backend/server-connection/pom.xml, backend/telemetry/pom.xml, buildSrc/maven-shade-ext-bnd-transformer/pom.xml, client/java-client-dependencies/pom.xml, client/java-client-osgi/pom.xml, client/java-client-utils/pom.xml, client/rpc-java-client/pom.xml, its/plugins/custom-sensor-plugin/pom.xml, its/plugins/global-extension-plugin/pom.xml, its/plugins/java-custom-rules/pom.xml, its/pom.xml, its/tests/pom.xml, medium-tests/pom.xml, pom.xml, report-aggregate/pom.xml, rpc-protocol/pom.xml, test-utils/pom.xml
[SLCORE-1653](https://sonarsource.atlassian.net/browse/SLCORE-1653)
[SLCORE-1653]: https://sonarsource.atlassian.net/browse/SLCORE-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1653 Prepare next dev iteration

backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/AnalysisTempFolderProvider.java, backend/analysis-engine/src/main/java/org/sonarsource/sonarlint/core/analysis/container/analysis/issue/ignore/IgnoreIssuesFilter.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/analysis/AnalysisTempFolderProviderTests.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/analysis/issue/ignore/EnforceIssuesFilterTests.java, backend/analysis-engine/src/test/java/org/sonarsource/sonarlint/core/analysis/container/analysis/issue/ignore/scanner/IssueExclusionsRegexpScannerTests.java, backend/commons/src/main/java/org/sonarsource/sonarlint/core/commons/api/progress/package-info.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/embedded/server/RequestHandlerBindingAssistant.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/fs/package-info.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/rules/RuleDetails.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowFixSuggestionRequestHandlerTests.java, backend/core/src/test/java/org/sonarsource/sonarlint/core/embedded/server/ShowIssueRequestHandlerTests.java, backend/plugin-commons/src/main/java/org/sonar/api/package-info.java, backend/plugin-commons/src/main/java/org/sonarsource/sonarlint/core/plugin/commons/MultivalueProperty.java, backend/plugin-commons/src/test/java/org/sonarsource/sonarlint/core/plugin/commons/MultivaluePropertyTests.java, backend/plugin-commons/src/test/java/org/sonarsource/sonarlint/core/plugin/commons/Utils.java, backend/plugin-commons/src/test/java/org/sonarsource/sonarlint/core/plugin/commons/sonarapi/MapSettingsTests.java, backend/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/push/parsing/package-info.java, backend/server-api/src/test/java/org/sonarsource/sonarlint/core/serverapi/hotspot/HotspotApiTests.java, medium-tests/src/test/java/mediumtest/StandaloneIssueMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/connection/auth/package-info.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/connection/common/package-info.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/connection/validate/package-info.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/fs/package-info.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/smartnotification/package-info.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/taint/vulnerability/package-info.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/client/telemetry/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintBackendFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ProjectStorageFixture.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/storage/ServerIssueFixtures.java
[SLCORE-1634](https://sonarsource.atlassian.net/browse/SLCORE-1634)
[SLCORE-1634]: https://sonarsource.atlassian.net/browse/SLCORE-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1634 Fix code smells

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, its/tests/src/test/java/its/FileExclusionTests.java, its/tests/src/test/java/its/SonarQubeDeveloperEditionTests.java, medium-tests/src/test/java/mediumtest/analysis/AnalysisReadinessMediumTests.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/server/ServerFixture.java
[SLCORE-1619](https://sonarsource.atlassian.net/browse/SLCORE-1619)
[SLCORE-1619]: https://sonarsource.atlassian.net/browse/SLCORE-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1619 Trigger a new analysis when binding changes

API_CHANGES.md, backend/core/src/main/java/org/sonarsource/sonarlint/core/ai/ide/AiAssistedIdeService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/ai/ide/package-info.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/spring/SonarLintSpringAppConfig.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/AiAssistedIdeRpcServiceDelegate.java, backend/rpc-impl/src/main/java/org/sonarsource/sonarlint/core/rpc/impl/SonarLintRpcServerImpl.java, medium-tests/src/test/java/mediumtest/ai/ide/AiAssistedIdeMediumTests.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/SonarLintRpcServer.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/ai/AiAssistedIde.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/ai/AiAssistedIdeRpcService.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/ai/GetRuleFileContentParams.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/ai/GetRuleFileContentResponse.java, rpc-protocol/src/main/java/org/sonarsource/sonarlint/core/rpc/protocol/backend/ai/package-info.java, test-utils/src/main/java/org/sonarsource/sonarlint/core/test/utils/SonarLintTestRpcServer.java
[SLCORE-1651](https://sonarsource.atlassian.net/browse/SLCORE-1651)
[SLCORE-1651]: https://sonarsource.atlassian.net/browse/SLCORE-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1651 Add support for on-demand rule file creation for AI-assisted IDEs

backend/core/src/main/java/org/sonarsource/sonarlint/core/analysis/AnalysisService.java, backend/core/src/main/java/org/sonarsource/sonarlint/core/repository/config/ConfigurationRepository.java
[SLCORE-1619](https://sonarsource.atlassian.net/browse/SLCORE-1619)
[SLCORE-1619]: https://sonarsource.atlassian.net/browse/SLCORE-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLCORE-1619 Notify client of readiness change when scope removed
